import { useState } from 'react';

export default function PartnerOrigination5YearGuide() {
  const [homesPerYear, setHomesPerYear] = useState(15);
  const [avgJobsPerHome, setAvgJobsPerHome] = useState(2.5);

  const ratePerJob = 18;
  const growthRate = 0.12;

  const years = [1, 2, 3, 4, 5].map((yr) => {
    const cumulativeHomes = homesPerYear * yr;
    const activeHomes = Math.round(cumulativeHomes * (1 - 0.05 * (yr - 1)));
    const jobsThisYear = Math.round(activeHomes * avgJobsPerHome * (1 + growthRate * (yr - 1)));
    const income = Math.round(jobsThisYear * ratePerJob);
    return { yr, cumulativeHomes, activeHomes, jobsThisYear, income };
  });

  const totalIncome = years.reduce((sum, y) => sum + y.income, 0);
  const maxIncome = Math.max(...years.map(y => y.income));

  return (
    <div style={{ background: '#F9FAFB', minHeight: '100vh', padding: '32px 16px', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ maxWidth: 820, margin: '0 auto' }}>
        <div style={{ background: '#0A1628', borderRadius: 16, padding: '32px', marginBottom: 24, color: 'white' }}>
          <div style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>🏠 5-Year Origination Rights Guide</div>
          <div style={{ color: '#94A3B8', fontSize: 15 }}>How origination rights become your permanent residual income stream — growing every year</div>
        </div>

        <div style={{ background: '#F0FDF4', border: '1px solid #BBF7D0', borderRadius: 12, padding: 20, marginBottom: 24 }}>
          <div style={{ fontWeight: 700, color: '#065F46', fontSize: 15, marginBottom: 8 }}>🔑 What Are Origination Rights?</div>
          <div style={{ color: '#047857', fontSize: 13, lineHeight: 1.6 }}>
            When you bring a home into the ProLnk Home Health Vault, you earn a permanent share of the platform fees generated by that home — forever. Every time a ProLnk job is matched at that property, you earn a residual cut. This compounds as you add more homes and as ProLnk grows in your market.
          </div>
        </div>

        <div style={{ background: 'white', borderRadius: 12, padding: 24, marginBottom: 24, border: '1px solid #E5E7EB' }}>
          <div style={{ fontWeight: 700, fontSize: 16, color: '#0A1628', marginBottom: 16 }}>⚙️ Configure Your Origination Plan</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
            <div>
              <label style={{ fontSize: 13, color: '#6B7280', display: 'block', marginBottom: 6 }}>Homes Added Per Year: {homesPerYear}</label>
              <input type="range" min={1} max={100} value={homesPerYear} onChange={e => setHomesPerYear(Number(e.target.value))} style={{ width: '100%', accentColor: '#F5E642′ }} />
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#9CA3AF', marginTop: 2 }}>
                <span>1 home</span><span>100 homes</span>
              </div>
            </div>
            <div>
              <label style={{ fontSize: 13, color: '#6B7280', display: 'block', marginBottom: 6 }}>Avg Jobs Per Home/Year: {avgJobsPerHome}</label>
              <input type="range" min={1} max={6} step={0.5} value={avgJobsPerHome} onChange={e => setAvgJobsPerHome(Number(e.target.value))} style={{ width: '100%', accentColor: '#F5E642′ }} />
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#9CA3AF', marginTop: 2 }}>
                <span>1x</span><span>6x</span>
              </div>
            </div>
          </div>
        </div>

        <div style={{ background: 'white', borderRadius: 12, padding: 24, marginBottom: 24, border: '1px solid #E5E7EB' }}>
          <div style={{ fontWeight: 700, fontSize: 16, color: '#0A1628', marginBottom: 20 }}>📈 Year-by-Year Origination Income</div>
          {years.map((y, i) => (
            <div key={i} style={{ marginBottom: 20 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                <div>
                  <span style={{ fontWeight: 700, color: '#0A1628', fontSize: 15 }}>Year {y.yr}</span>
                  <span style={{ color: '#6B7280', fontSize: 12, marginLeft: 10 }}>{y.cumulativeHomes} homes in vault • {y.jobsThisYear} jobs matched</span>
                </div>
                <span style={{ fontWeight: 800, color: '#F59E0B', fontSize: 18 }}>${y.income.toLocaleString()}</span>
              </div>
              <div style={{ background: '#F3F4F6', borderRadius: 6, height: 12, overflow: 'hidden' }}>
                <div style={{ width: `${Math.round((y.income / maxIncome) * 100)}%`, height: '100%', background: `linear-gradient(90deg, #F59E0B, #F5E642)`, borderRadius: 6 }} />
              </div>
            </div>
          ))}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, marginBottom: 24 }}>
          <div style={{ background: '#0A1628', borderRadius: 12, padding: 20, textAlign: 'center', color: 'white' }}>
            <div style={{ fontSize: 12, color: '#94A3B8', marginBottom: 6 }}>5-Year Cumulative</div>
            <div style={{ fontSize: 30, fontWeight: 800, color: '#F5E642′ }}>${totalIncome.toLocaleString()}</div>
          </div>
          <div style={{ background: 'white', borderRadius: 12, padding: 20, textAlign: 'center', border: '1px solid #E5E7EB' }}>
            <div style={{ fontSize: 12, color: '#6B7280', marginBottom: 6 }}>Year 5 Annual Run Rate</div>
            <div style={{ fontSize: 30, fontWeight: 800, color: '#059669′ }}>${years[4].income.toLocaleString()}</div>
          </div>
          <div style={{ background: 'white', borderRadius: 12, padding: 20, textAlign: 'center', border: '1px solid #E5E7EB' }}>
            <div style={{ fontSize: 12, color: '#6B7280', marginBottom: 6 }}>Total Homes in Vault</div>
            <div style={{ fontSize: 30, fontWeight: 800, color: '#3B82F6′ }}>{homesPerYear * 5}</div>
          </div>
        </div>

        <div style={{ background: 'white', borderRadius: 12, padding: 24, marginBottom: 16, border: '1px solid #E5E7EB' }}>
          <div style={{ fontWeight: 700, color: '#0A1628', marginBottom: 12 }}>♾️ The Permanent Nature of Origination Rights</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            {[
              { icon: '🏠', text: 'Rights attach to the property address, not just one transaction' },
              { icon: '📅', text: 'Income continues as long as ProLnk operates in that market' },
              { icon: '📈', text: 'Grows as ProLnk adds more service categories per home' },
              { icon: '🔄', text: 'Not affected by homeowner changes — address stays in vault' },
            ].map((item, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, padding: 12, background: '#F9FAFB', borderRadius: 8 }}>
                <span style={{ fontSize: 20 }}>{item.icon}</span>
                <span style={{ fontSize: 13, color: '#374151', lineHeight: 1.5 }}>{item.text}</span>
              </div>
            ))}
          </div>
        </div>

        <div style={{ background: '#FFFBEB', border: '1px solid #F5E642', borderRadius: 12, padding: 16, fontSize: 13, color: '#78350F' }}>
          💡 Origination income assumes $18/job residual at current rate. Rates subject to adjustment as platform scales. Jobs-per-home based on DFW market averages.
        </div>
      </div>
    </div>
  );
}
