import { useState } from 'react';

const faqs = [
  {
    q: 'How do commissions work?',
    a: 'You earn a percentage of every job matched through your link or under your network. Direct matches earn 12% of the job value. Your override rates for network jobs range from 7% (Level 1) to 1% (Level 4). Subscription overrides add 12% of monthly dues from anyone you personally recruited.',
  },
  {
    q: 'When do I get paid?',
    a: 'Commissions are calculated monthly and paid out by the 15th of the following month. For example, April earnings are paid by May 15. Payouts are sent via ACH direct deposit or check. Minimum payout threshold is $25.',
  },
  {
    q: 'What if a client doesn\’t pay?',
    a: 'You earn commissions only on completed and paid jobs. If a homeowner cancels before the job is finished or disputes a payment, the commission on that job is held pending resolution. Chargebacks that are reversed are retroactively credited to your account.',
  },
  {
    q: 'Can I partner with family members?',
    a: 'Yes. Family members can sign up as partners under you and your override applies normally. However, self-dealing (signing up fake accounts or routing your own transactions) is against our terms and will result in account termination and commission forfeiture.',
  },
  {
    q: 'How does the 4-level override work?',
    a: 'When you recruit Partner A, and A recruits Partner B, you earn a Level 2 override on B\’s job commissions. This cascades 4 levels deep: Level 1 = 7%, Level 2 = 4%, Level 3 = 2%, Level 4 = 1%. Network income compounds as your downline grows.',
  },
  {
    q: 'What is a "matching fee"?',
    a: 'A matching fee is the platform charge collected when a homeowner is matched with a pro for a service job. Typically this is 15–20% of the agreed job value. Your commission is calculated as a percentage of this fee, not of the total job price.',
  },
  {
    q: 'Do I need a license to be a partner?',
    a: 'No license is required to be a ProLnk Partner. You are a referral and network affiliate, not a licensed contractor. However, if you recruit licensed pros or homeowners, you must be honest about what the platform offers and not make income guarantees.',
  },
  {
    q: 'How do I recruit other partners?',
    a: 'Share your unique partner referral link. Anyone who signs up using your link becomes your Level 1 partner and you earn a 7% job override and 12% subscription override on their activity. Use the Marketing Kit for scripts and templates.',
  },
  {
    q: 'What is the Home Health Vault?',
    a: 'The Home Health Vault is ProLnk\’s proprietary home data asset. It stores structural, safety, and maintenance history for homes. When you originate a home (get a homeowner to register their property), you earn a permanent 1.5% origination right on future platform revenue from that home.',
  },
  {
    q: 'What is an origination right?',
    a: 'An origination right is a permanent, recurring override on any future matching fees generated by a home you originally brought into the vault. Charter Partners earn 1.5%; Founding Partners earn 1.0%. These persist even if you go inactive.',
  },
  {
    q: 'Is there a cap on my earnings?',
    a: 'No. There is no cap on your earnings. The more jobs you match, the more partners you recruit, and the more homes you originate, the more you earn. Top partners earn five and six figures monthly.',
  },
  {
    q: 'Can I lose my tier status?',
    a: 'Your tier is locked at signup for Charter and Founding members during the waitlist period. After launch, tiers may be performance-gated based on monthly minimums. Your Partnership Agreement will specify any maintenance requirements.',
  },
  {
    q: 'What happens if I want to cancel?',
    a: 'You can cancel your partner subscription at any time with 30 days written notice. Earned commissions through your cancellation date will be paid on the normal schedule. Origination rights accumulated before cancellation are retained for 12 months and then expire.',
  },
  {
    q: 'Are there refunds on the monthly fee?',
    a: 'The $149/month partner fee is non-refundable after the 7-day trial period. This fee covers platform access, lead tracking tools, partner training resources, and your commission engine.',
  },
  {
    q: 'How do I track my earnings?',
    a: 'Your partner dashboard shows real-time commission accruals, partner tree activity, origination rights, and payout history. You can export monthly statements for tax purposes.',
  },
  {
    q: 'Do I receive a 1099?',
    a: 'Yes. If your annual earnings exceed $600, you will receive a 1099-NEC form by January 31 of the following tax year. Partners earning over $20,000 should work with a tax advisor on quarterly estimated payments.',
  },
  {
    q: 'Can I be a partner and a pro?',
    a: 'Yes. You can operate as both a network partner and a licensed service professional on the platform. Your partner commissions and your pro earnings are tracked separately and do not interfere with each other.',
  },
  {
    q: 'What trades does ProLnk serve?',
    a: 'ProLnk serves all major home service trades: plumbing, HVAC, electrical, roofing, flooring, painting, landscaping, pest control, general contracting, and more. The platform is expanding into specialty trades through 2026.',
  },
  {
    q: 'How does ProLnk protect homeowner data?',
    a: 'ProLnk is CCPA and GDPR compliant. Homeowner data is encrypted at rest and in transit. Partners do not have access to raw homeowner PII — only aggregate match statistics relevant to your commissions are visible in your dashboard.',
  },
  {
    q: 'What support does ProLnk offer partners?',
    a: 'Every partner is assigned a Partner Success Manager for the first 90 days. Ongoing support includes weekly webinars, a community Slack, monthly 1-on-1 check-ins for Charter/Founding members, and a dedicated support email with 24-hour response SLA.',
  },
];

export default function PartnerFAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div style={{ backgroundColor: '#F9FAFB', minHeight: '100vh', padding: '40px 20px', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ maxWidth: 760, margin: '0 auto' }}>
        <div style={{ marginBottom: 32 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
            <span style={{ fontSize: 32 }}>❓</span>
            <h1 style={{ fontSize: 28, fontWeight: 800, color: '#0A1628', margin: 0 }}>Partner FAQ</h1>
          </div>
          <p style={{ color: '#64748B', fontSize: 15, margin: 0 }}>
            Answers to the 20 most common questions from new and prospective partners.
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {faqs.map((faq, i) => (
            <div
              key={i}
              style={{ backgroundColor: '#fff', borderRadius: 12, border: open === i ? '1.5px solid #F5E642' : '1px solid #E2E8F0', overflow: 'hidden' }}
            >
              <button
                onClick={() => setOpen(open === i ? null : i)}
                style={{
                  width: '100%',
                  textAlign: 'left',
                  background: 'none',
                  border: 'none',
                  padding: '16px 20px',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  cursor: 'pointer',
                  gap: 12,
                }}
              >
                <span style={{ fontWeight: 600, color: '#0A1628', fontSize: 15 }}>{faq.q}</span>
                <span style={{ fontSize: 18, color: '#94A3B8', flexShrink: 0 }}>{open === i ? '▲' : '▼'}</span>
              </button>
              {open === i && (
                <div style={{ padding: '0 20px 20px', color: '#374151', fontSize: 14, lineHeight: 1.7 }}>
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>

        <div style={{ marginTop: 32, backgroundColor: '#0A1628', borderRadius: 12, padding: 24, textAlign: 'center' }}>
          <p style={{ color: '#94A3B8', margin: '0 0 12px', fontSize: 14 }}>Still have questions?</p>
          <p style={{ color: '#F5E642', fontWeight: 700, fontSize: 16, margin: 0 }}>
            📧 Email partners@prolnk.io — 24-hour response guaranteed
          </p>
        </div>
      </div>
    </div>
  );
}
