-- Sprint 8 Waves Migration
-- New tables: fsmWebhookEvents, webhookSubscriptions, webhookDeliveryLog,
--             proAgreements, propertyProfiles, partnerPerformanceScores,
--             aiTrainingDataset, funnelEvents, referralGraph,
--             geographicDensity, acceptanceSignals, partnerIntegrations,
--             photoIntakeQueue, homeownerProfiles, properties,
--             propertyImprovements, propertyWishes, propertyPhotos,
--             customerDeals, partnerReviews, homeownerReviews,
--             activityLog, partnerNotifications, industryRates, jobs,
--             opportunities

CREATE TABLE `fsmWebhookEvents` (
  `id` int AUTO_INCREMENT NOT NULL,
  `source` enum('housecall_pro','jobber','workiz','service_fusion','fieldedge','other') NOT NULL,
  `eventType` varchar(100) NOT NULL,
  `externalJobId` varchar(255),
  `leadSourceTag` varchar(100),
  `matchedPartnerId` int,
  `matchedOpportunityId` int,
  `jobValue` decimal(10,2),
  `status` enum('received','matched','unmatched','commission_closed','error') NOT NULL DEFAULT 'received',
  `errorMessage` text,
  `rawPayload` json,
  `processedAt` timestamp,
  `receivedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `fsmWebhookEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webhookSubscriptions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(255) NOT NULL,
  `url` text NOT NULL,
  `secret` varchar(255),
  `events` json,
  `isActive` boolean NOT NULL DEFAULT true,
  `totalFired` int NOT NULL DEFAULT 0,
  `totalSucceeded` int NOT NULL DEFAULT 0,
  `totalFailed` int NOT NULL DEFAULT 0,
  `lastFiredAt` timestamp,
  `lastStatus` int,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `webhookSubscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webhookDeliveryLog` (
  `id` int AUTO_INCREMENT NOT NULL,
  `subscriptionId` int NOT NULL,
  `eventName` varchar(100) NOT NULL,
  `payload` json,
  `statusCode` int,
  `responseBody` text,
  `success` boolean NOT NULL DEFAULT false,
  `durationMs` int,
  `firedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `webhookDeliveryLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proAgreements` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `templateVersion` varchar(20) NOT NULL DEFAULT 'v1.0',
  `tierAtSigning` enum('scout','pro','crew','company','enterprise') NOT NULL,
  `commissionRateAtSigning` decimal(5,4) NOT NULL,
  `effectiveDate` timestamp NOT NULL,
  `status` enum('pending','sent','signed','expired','voided') NOT NULL DEFAULT 'pending',
  `signedAt` timestamp,
  `signerName` varchar(255),
  `signatureData` text,
  `ipAddress` varchar(64),
  `pdfS3Key` varchar(500),
  `pdfUrl` text,
  `sentAt` timestamp,
  `sentVia` enum('email','in_app','manual'),
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `proAgreements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `propertyProfiles` (
  `id` int AUTO_INCREMENT NOT NULL,
  `address` text NOT NULL,
  `city` varchar(100),
  `state` varchar(50),
  `zip` varchar(20),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `homeownerName` varchar(255),
  `homeownerPhone` varchar(30),
  `homeownerEmail` varchar(255),
  `totalJobsLogged` int NOT NULL DEFAULT 0,
  `totalOpportunitiesDetected` int NOT NULL DEFAULT 0,
  `totalOffersAccepted` int NOT NULL DEFAULT 0,
  `totalOffersDeclined` int NOT NULL DEFAULT 0,
  `totalRevenueGenerated` decimal(12,2) DEFAULT '0.00',
  `tradesServiced` json,
  `detectionHistory` json,
  `avgAcceptedDiscountPct` decimal(5,2),
  `lastServicedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `propertyProfiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partnerPerformanceScores` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `totalLeadsReceived` int NOT NULL DEFAULT 0,
  `totalLeadsAccepted` int NOT NULL DEFAULT 0,
  `totalLeadsDeclined` int NOT NULL DEFAULT 0,
  `totalLeadsClosed` int NOT NULL DEFAULT 0,
  `leadAcceptanceRate` decimal(5,4) NOT NULL DEFAULT '0',
  `leadCloseRate` decimal(5,4) NOT NULL DEFAULT '0',
  `avgResponseTimeHours` decimal(8,2),
  `avgJobValue` decimal(10,2),
  `totalJobValueClosed` decimal(12,2) NOT NULL DEFAULT '0',
  `totalCommissionsEarned` decimal(12,2) NOT NULL DEFAULT '0',
  `totalCommissionsPaid` decimal(12,2) NOT NULL DEFAULT '0',
  `totalReferralsSent` int NOT NULL DEFAULT 0,
  `totalReferralsConverted` int NOT NULL DEFAULT 0,
  `referralConversionRate` decimal(5,4) NOT NULL DEFAULT '0',
  `healthScore` int DEFAULT 50,
  `churnRisk` enum('low','medium','high') DEFAULT 'low',
  `lastJobLoggedAt` timestamp,
  `lastLeadAcceptedAt` timestamp,
  `calculatedAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partnerPerformanceScores_id` PRIMARY KEY(`id`),
  CONSTRAINT `partnerPerformanceScores_partnerId_unique` UNIQUE(`partnerId`)
);
--> statement-breakpoint
CREATE TABLE `aiTrainingDataset` (
  `id` int AUTO_INCREMENT NOT NULL,
  `jobId` int,
  `opportunityId` int,
  `beforePhotoUrl` text,
  `afterPhotoUrl` text,
  `detectionType` varchar(100) NOT NULL,
  `detectionCategory` varchar(100) NOT NULL,
  `aiConfidenceScore` decimal(4,3),
  `validationOutcome` enum('validated','rejected','pending','unknown') DEFAULT 'pending',
  `propertyType` varchar(50),
  `propertyZip` varchar(20),
  `propertyState` varchar(50),
  `capturedMonth` int,
  `capturedSeason` enum('spring','summer','fall','winter'),
  `modelVersion` varchar(50) DEFAULT 'v1',
  `approvedForTraining` boolean DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `aiTrainingDataset_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `geographicDensity` (
  `id` int AUTO_INCREMENT NOT NULL,
  `zip` varchar(20) NOT NULL,
  `city` varchar(100),
  `state` varchar(50),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `snapshotDate` timestamp NOT NULL,
  `totalActivePartners` int DEFAULT 0,
  `totalTradesCovered` int DEFAULT 0,
  `tradeBreakdown` json,
  `totalJobsLogged` int DEFAULT 0,
  `totalOpportunitiesDetected` int DEFAULT 0,
  `totalOffersAccepted` int DEFAULT 0,
  `coverageGapScore` int DEFAULT 0,
  `unmetDemandTrades` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `geographicDensity_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `acceptanceSignals` (
  `id` int AUTO_INCREMENT NOT NULL,
  `opportunityId` int NOT NULL,
  `propertyProfileId` int,
  `tradeCategory` varchar(100) NOT NULL,
  `offerAmount` decimal(10,2),
  `standardMarketPrice` decimal(10,2),
  `discountPct` decimal(5,2),
  `outcome` enum('accepted','declined','ignored','expired') NOT NULL,
  `timeToRespondHours` decimal(8,2),
  `deliveryChannel` enum('sms','email','push','in_app'),
  `deliveryHourOfDay` int,
  `deliveryDayOfWeek` int,
  `deliveryMonth` int,
  `deliverySeason` enum('spring','summer','fall','winter'),
  `propertyZip` varchar(20),
  `propertyCity` varchar(100),
  `propertyState` varchar(50),
  `isFirstOffer` boolean DEFAULT true,
  `priorOfferCount` int DEFAULT 0,
  `recordedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `acceptanceSignals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partnerIntegrations` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `source` varchar(50) NOT NULL,
  `accessToken` text,
  `refreshToken` text,
  `tokenExpiresAt` timestamp,
  `externalAccountId` varchar(255),
  `externalAccountName` varchar(255),
  `webhookId` varchar(255),
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `lastSyncAt` timestamp,
  `errorMessage` text,
  `metadata` text,
  `connectedAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partnerIntegrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `photoIntakeQueue` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `integrationId` int,
  `source` varchar(50) NOT NULL,
  `photoUrl` text NOT NULL,
  `thumbnailUrl` text,
  `photoHash` varchar(64),
  `externalJobId` varchar(255),
  `externalJobName` varchar(500),
  `serviceAddress` text,
  `serviceCity` varchar(100),
  `serviceZip` varchar(20),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `jobId` int,
  `aiResult` text,
  `processedAt` timestamp,
  `errorMessage` text,
  `capturedAt` timestamp,
  `receivedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `photoIntakeQueue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `homeownerProfiles` (
  `id` int AUTO_INCREMENT NOT NULL,
  `userId` int NOT NULL,
  `displayName` varchar(255),
  `phone` varchar(30),
  `bio` text,
  `photoUrl` text,
  `setupComplete` boolean NOT NULL DEFAULT false,
  `contactPreference` enum('email','text','phone','in_app') DEFAULT 'email',
  `openToRecommendations` boolean NOT NULL DEFAULT true,
  `consentTerms` boolean NOT NULL DEFAULT false,
  `consentPhotos` boolean NOT NULL DEFAULT false,
  `consentPartnerContact` boolean NOT NULL DEFAULT false,
  `consentAiData` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `homeownerProfiles_id` PRIMARY KEY(`id`),
  CONSTRAINT `homeownerProfiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
  `id` int AUTO_INCREMENT NOT NULL,
  `ownerId` int NOT NULL,
  `nickname` varchar(100),
  `address` varchar(500) NOT NULL,
  `city` varchar(100),
  `state` varchar(50),
  `zip` varchar(20),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `propertyType` enum('single_family','condo','townhouse','multi_family','other') DEFAULT 'single_family',
  `yearBuilt` int,
  `sqft` int,
  `bedrooms` int,
  `bathrooms` decimal(3,1),
  `lotSize` enum('under_0_25','0_25_to_0_5','0_5_to_1','over_1'),
  `hasPool` boolean NOT NULL DEFAULT false,
  `hasGarage` boolean NOT NULL DEFAULT false,
  `garageType` enum('attached','detached','none') DEFAULT 'none',
  `hasFence` boolean NOT NULL DEFAULT false,
  `isPrimary` boolean NOT NULL DEFAULT true,
  `isRental` boolean NOT NULL DEFAULT false,
  `occupancy` enum('owner_occupied','tenant_occupied','vacant') DEFAULT 'owner_occupied',
  `ownershipYears` enum('under_1','1_to_3','3_to_7','7_to_15','over_15'),
  `hiringPriorities` json,
  `setupStep` int NOT NULL DEFAULT 1,
  `setupComplete` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `propertyImprovements` (
  `id` int AUTO_INCREMENT NOT NULL,
  `propertyId` int NOT NULL,
  `category` varchar(100) NOT NULL,
  `completedYear` int,
  `hasWarranty` boolean NOT NULL DEFAULT false,
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `propertyImprovements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `propertyWishes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `propertyId` int NOT NULL,
  `category` varchar(100) NOT NULL,
  `budgetRange` enum('under_1k','1k_5k','5k_15k','15k_50k','over_50k','not_sure'),
  `urgency` enum('within_30_days','1_to_3_months','3_to_6_months','6_to_12_months','just_researching'),
  `preferredTimeline` varchar(100),
  `notes` text,
  `leadCreated` boolean NOT NULL DEFAULT false,
  `leadCreatedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `propertyWishes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `propertyPhotos` (
  `id` int AUTO_INCREMENT NOT NULL,
  `propertyId` int NOT NULL,
  `uploadedByUserId` int,
  `s3Key` varchar(500) NOT NULL,
  `url` text NOT NULL,
  `thumbnailUrl` text,
  `roomLabel` varchar(100),
  `caption` text,
  `aiScanned` boolean NOT NULL DEFAULT false,
  `aiSignals` json,
  `aiScannedAt` timestamp,
  `hasPetSignal` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `propertyPhotos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customerDeals` (
  `id` int AUTO_INCREMENT NOT NULL,
  `token` varchar(64) NOT NULL,
  `opportunityId` int NOT NULL,
  `referringPartnerId` int NOT NULL,
  `receivingPartnerId` int,
  `homeownerName` varchar(255),
  `homeownerEmail` varchar(320),
  `homeownerPhone` varchar(30),
  `homeownerAddress` text,
  `homeownerCity` varchar(100),
  `homeownerZip` varchar(20),
  `issueType` varchar(100) NOT NULL,
  `issueCategory` varchar(100) NOT NULL,
  `issueDescription` text NOT NULL,
  `issueDescriptionShort` varchar(100),
  `photoUrl` varchar(1000),
  `photoUrls` json,
  `signatureData` text,
  `signedAt` int,
  `signerName` varchar(255),
  `aiConfidence` int,
  `estimatedValueLow` decimal(10,2),
  `estimatedValueHigh` decimal(10,2),
  `homeownerMessageSnippet` text,
  `status` enum('draft','sent','viewed','scheduled','estimate_done','accepted','job_closed','declined','expired') NOT NULL DEFAULT 'draft',
  `scheduledAt` timestamp,
  `scheduleConfirmedAt` timestamp,
  `calBookingId` varchar(255),
  `expiresAt` timestamp,
  `viewCount` int NOT NULL DEFAULT 0,
  `firstViewedAt` timestamp,
  `lastViewedAt` timestamp,
  `emailSentAt` timestamp,
  `smsSentAt` timestamp,
  `emailOpenedAt` timestamp,
  `actualJobValue` decimal(10,2),
  `jobClosedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `customerDeals_id` PRIMARY KEY(`id`),
  CONSTRAINT `customerDeals_token_unique` UNIQUE(`token`)
);
--> statement-breakpoint
CREATE TABLE `partnerReviews` (
  `id` int AUTO_INCREMENT NOT NULL,
  `dealId` int NOT NULL,
  `partnerId` int NOT NULL,
  `homeownerName` varchar(255),
  `homeownerEmail` varchar(320),
  `rating` int NOT NULL,
  `reviewText` text,
  `ratingPunctuality` int,
  `ratingQuality` int,
  `ratingCommunication` int,
  `ratingValue` int,
  `googleReviewRequested` boolean NOT NULL DEFAULT false,
  `googleReviewRequestedAt` timestamp,
  `yelpReviewRequested` boolean NOT NULL DEFAULT false,
  `isPublic` boolean NOT NULL DEFAULT true,
  `flagged` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `partnerReviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `homeownerReviews` (
  `id` int AUTO_INCREMENT NOT NULL,
  `dealId` int NOT NULL,
  `partnerId` int NOT NULL,
  `homeownerEmail` varchar(320),
  `homeownerName` varchar(255),
  `rating` int NOT NULL,
  `reviewText` text,
  `ratingReliability` int,
  `ratingCommunication` int,
  `ratingPayment` int,
  `isPublic` boolean NOT NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `homeownerReviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `activityLog` (
  `id` int AUTO_INCREMENT NOT NULL,
  `eventType` varchar(64) NOT NULL,
  `actorId` int,
  `actorName` varchar(128),
  `actorRole` enum('admin','partner','homeowner','system') NOT NULL DEFAULT 'system',
  `entityType` varchar(64),
  `entityId` int,
  `entityName` varchar(255),
  `description` text NOT NULL,
  `metadata` json,
  `ipAddress` varchar(64),
  `createdAt` timestamp DEFAULT (now()),
  CONSTRAINT `activityLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partnerNotifications` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `type` enum('new_lead','lead_expired','commission_paid','approval','broadcast','system') NOT NULL DEFAULT 'system',
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `actionUrl` varchar(512),
  `isRead` boolean NOT NULL DEFAULT false,
  `metadata` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `partnerNotifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opportunities` (
  `id` int AUTO_INCREMENT NOT NULL,
  `jobId` int,
  `sourcePartnerId` int NOT NULL,
  `receivingPartnerId` int,
  `opportunityType` varchar(100) NOT NULL,
  `opportunityCategory` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `aiConfidence` int DEFAULT 0,
  `photoUrl` text,
  `adminReviewStatus` enum('pending','approved','rejected') DEFAULT 'pending',
  `adminReviewedAt` timestamp,
  `adminReviewedBy` int,
  `status` enum('pending_review','approved','dispatched','accepted','declined','expired','closed') NOT NULL DEFAULT 'pending_review',
  `leadExpiresAt` timestamp,
  `routingQueue` json,
  `routingPosition` int DEFAULT 0,
  `estimatedJobValue` decimal(10,2),
  `actualJobValue` decimal(10,2),
  `platformFeeAmount` decimal(10,2),
  `referralCommissionAmount` decimal(10,2),
  `proLinkNetAmount` decimal(10,2),
  `jobClosedAt` timestamp,
  `sentAt` timestamp,
  `acceptedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerId` int NOT NULL,
  `externalJobId` varchar(255),
  `source` varchar(50) NOT NULL DEFAULT 'manual',
  `jobTitle` varchar(500),
  `serviceAddress` text,
  `serviceCity` varchar(100),
  `serviceZip` varchar(20),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `status` varchar(30) NOT NULL DEFAULT 'open',
  `jobValue` decimal(10,2),
  `completedAt` timestamp,
  `notes` text,
  `metadata` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `industryRates` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tradeCategory` varchar(100) NOT NULL,
  `serviceType` varchar(100),
  `region` varchar(100) DEFAULT 'DFW',
  `lowEstimate` decimal(10,2) NOT NULL,
  `midEstimate` decimal(10,2) NOT NULL,
  `highEstimate` decimal(10,2) NOT NULL,
  `unit` varchar(50) DEFAULT 'job',
  `source` varchar(255),
  `effectiveYear` int DEFAULT 2025,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `industryRates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `referralGraph` (
  `id` int AUTO_INCREMENT NOT NULL,
  `sourcePartnerId` int NOT NULL,
  `receivingPartnerId` int NOT NULL,
  `sourceTrade` varchar(100),
  `receivingTrade` varchar(100),
  `city` varchar(100),
  `zip` varchar(20),
  `totalReferrals` int NOT NULL DEFAULT 0,
  `totalConverted` int NOT NULL DEFAULT 0,
  `totalJobValue` decimal(12,2) NOT NULL DEFAULT '0',
  `totalCommissionPaid` decimal(12,2) NOT NULL DEFAULT '0',
  `conversionRate` decimal(5,4) NOT NULL DEFAULT '0',
  `avgDaysToClose` decimal(6,2),
  `relationshipStrength` int DEFAULT 0,
  `firstReferralAt` timestamp,
  `lastReferralAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `referralGraph_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `funnelEvents` (
  `id` int AUTO_INCREMENT NOT NULL,
  `opportunityId` int NOT NULL,
  `propertyProfileId` int,
  `partnerId` int,
  `eventType` enum('ai_detected','admin_approved','offer_composed','notification_sent','notification_opened','page_visited','offer_clicked','offer_accepted','offer_declined','job_booked','job_completed','commission_paid') NOT NULL,
  `channel` enum('sms','email','push','in_app'),
  `offerAmount` decimal(10,2),
  `discountPct` decimal(5,2),
  `secondsFromPreviousEvent` int,
  `deviceType` varchar(50),
  `metadata` text,
  `occurredAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `funnelEvents_id` PRIMARY KEY(`id`)
);
