/**
 * ProLnk Service Categories
 * 60+ home service verticals with deep AI visual opportunity detection logic.
 * Each category defines:
 *   - id: unique slug used in DB and routing
 *   - name: display name
 *   - icon: lucide-react icon name
 *   - color: tailwind color class for UI
 *   - group: top-level grouping
 *   - avgJobValue: typical job value in USD
 *   - platformFeeRate: ProLnk's cut (decimal)
 *   - referralCommissionRate: referring partner's cut (decimal)
 *   - aiDetectionCues: what AI Vision Module looks for in photos to trigger this category
 *   - crossSellFrom: which other categories most commonly generate leads for this one
 */

export interface ServiceCategory {
  id: string;
  name: string;
  icon: string;
  color: string;
  group: string;
  avgJobValue: number;
  platformFeeRate: number;
  referralCommissionRate: number;
  aiDetectionCues: string[];
  crossSellFrom: string[];
  description: string;
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  // ─── LAWN & OUTDOOR ──────────────────────────────────────────────────────
  {
    id: "lawn_care",
    name: "Lawn Care & Mowing",
    icon: "Scissors",
    color: "text-green-600",
    group: "Lawn & Outdoor",
    avgJobValue: 150,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "grass height exceeds 4 inches or appears overgrown",
      "uneven lawn surface or bare patches visible",
      "weeds visible throughout lawn area",
      "lawn edges not trimmed along sidewalk or driveway",
      "lawn discoloration or yellowing indicating disease or drought stress",
    ],
    crossSellFrom: ["pet_waste_removal", "pool_cleaning", "pest_control", "irrigation"],
    description: "Mowing, edging, trimming, and general lawn maintenance",
  },
  {
    id: "landscaping",
    name: "Landscaping & Design",
    icon: "Trees",
    color: "text-green-700",
    group: "Lawn & Outdoor",
    avgJobValue: 2500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "overgrown or untrimmed shrubs and hedges",
      "bare mulch beds with no plants or depleted mulch",
      "dead or dying trees or large shrubs",
      "no defined landscape border or edging",
      "missing or sparse plants in visible garden beds",
      "outdated or mismatched landscape design",
    ],
    crossSellFrom: ["lawn_care", "irrigation", "drainage", "hardscaping", "outdoor_lighting"],
    description: "Full landscape design, planting, and installation",
  },
  {
    id: "tree_service",
    name: "Tree Service & Removal",
    icon: "TreePine",
    color: "text-emerald-700",
    group: "Lawn & Outdoor",
    avgJobValue: 1200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dead branches or limbs visible in tree canopy",
      "tree leaning at unsafe angle toward structure",
      "tree roots visibly lifting sidewalk, driveway, or foundation",
      "large tree overhanging roof or power lines",
      "tree stump visible in yard",
      "storm damage to tree branches",
    ],
    crossSellFrom: ["lawn_care", "landscaping", "storm_cleanup"],
    description: "Tree trimming, removal, stump grinding, and emergency service",
  },
  {
    id: "irrigation",
    name: "Irrigation & Sprinkler Systems",
    icon: "Droplets",
    color: "text-blue-500",
    group: "Lawn & Outdoor",
    avgJobValue: 800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dry or brown patches in lawn indicating irrigation gaps",
      "visible broken or tilted sprinkler heads",
      "water pooling or soggy areas indicating over-irrigation",
      "sprinkler head spraying sidewalk or driveway instead of lawn",
      "no visible irrigation system in established landscape",
    ],
    crossSellFrom: ["lawn_care", "landscaping", "drainage"],
    description: "Sprinkler installation, repair, and seasonal maintenance",
  },
  {
    id: "drainage",
    name: "Drainage & Grading",
    icon: "Waves",
    color: "text-blue-700",
    group: "Lawn & Outdoor",
    avgJobValue: 1800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "standing water or waterlogged areas in yard",
      "erosion channels or gullies visible in lawn or garden",
      "soil sloping toward foundation instead of away",
      "water stains on foundation or basement walls visible from exterior",
      "downspout discharging directly against foundation",
      "muddy or bare patches indicating poor drainage",
    ],
    crossSellFrom: ["lawn_care", "landscaping", "gutter_cleaning", "foundation_repair"],
    description: "French drains, grading, erosion control, and water management",
  },
  {
    id: "hardscaping",
    name: "Hardscaping & Patios",
    icon: "Square",
    color: "text-stone-600",
    group: "Lawn & Outdoor",
    avgJobValue: 5000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracked, heaved, or uneven patio pavers or concrete",
      "no patio or outdoor living space in large backyard",
      "old or deteriorated deck visible",
      "missing retaining wall or crumbling existing wall",
      "gravel driveway or bare dirt area that could be paved",
    ],
    crossSellFrom: ["landscaping", "outdoor_lighting", "fence_installation"],
    description: "Patios, walkways, retaining walls, driveways, and outdoor living spaces",
  },
  {
    id: "artificial_turf",
    name: "Artificial Turf Installation",
    icon: "Leaf",
    color: "text-lime-600",
    group: "Lawn & Outdoor",
    avgJobValue: 4500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "lawn with persistent bare patches or poor grass coverage",
      "high-traffic areas with worn-down grass",
      "pet run or dog area with muddy or dead grass",
      "shaded area where grass struggles to grow",
      "homeowner has dogs visible in yard (pet waste removal clients)",
    ],
    crossSellFrom: ["pet_waste_removal", "lawn_care", "landscaping"],
    description: "Synthetic grass installation for yards, pet areas, and putting greens",
  },
  {
    id: "outdoor_lighting",
    name: "Outdoor & Landscape Lighting",
    icon: "Lightbulb",
    color: "text-yellow-500",
    group: "Lawn & Outdoor",
    avgJobValue: 1500,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "no visible outdoor lighting in landscaped areas",
      "dark pathway or walkway with no lighting",
      "security gaps with no motion-activated lights",
      "outdated or broken light fixtures visible",
      "beautiful landscape that would benefit from accent lighting",
    ],
    crossSellFrom: ["landscaping", "hardscaping", "electrical"],
    description: "Landscape accent lighting, pathway lights, security lighting",
  },
  {
    id: "fence_installation",
    name: "Fence Installation & Repair",
    icon: "Fence",
    color: "text-amber-700",
    group: "Lawn & Outdoor",
    avgJobValue: 3000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "fence panels leaning, broken, or missing",
      "fence posts rotting or damaged at base",
      "gate not closing properly or off its hinges",
      "fence with peeling paint or significant weathering",
      "no fence on property that has dogs or children",
      "chain link fence that could be upgraded to privacy fence",
    ],
    crossSellFrom: ["pet_waste_removal", "lawn_care", "handyman"],
    description: "Wood, vinyl, aluminum, and chain link fence installation and repair",
  },
  {
    id: "pet_waste_removal",
    name: "Pet Waste Removal",
    icon: "PawPrint",
    color: "text-amber-600",
    group: "Lawn & Outdoor",
    avgJobValue: 120,
    platformFeeRate: 0.15,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dog visible in yard",
      "dog door or dog kennel visible",
      "dog waste bags or dispenser visible near fence",
      "multiple dogs visible",
    ],
    crossSellFrom: ["lawn_care", "landscaping", "artificial_turf"],
    description: "Regular dog waste cleanup and yard deodorizing",
  },

  // ─── POOL & WATER ─────────────────────────────────────────────────────────
  {
    id: "pool_cleaning",
    name: "Pool Cleaning & Maintenance",
    icon: "Waves",
    color: "text-cyan-500",
    group: "Pool & Water",
    avgJobValue: 200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "pool water appears green, cloudy, or discolored",
      "visible algae on pool walls or steps",
      "pool deck cracked or stained",
      "pool equipment (pump, filter) appears old or corroded",
      "pool cover damaged or missing",
      "pool visible but no service equipment present",
    ],
    crossSellFrom: ["pet_waste_removal", "lawn_care", "pest_control"],
    description: "Weekly pool cleaning, chemical balancing, and equipment maintenance",
  },
  {
    id: "pool_repair",
    name: "Pool Repair & Renovation",
    icon: "Wrench",
    color: "text-cyan-700",
    group: "Pool & Water",
    avgJobValue: 4000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "pool plaster cracked, chipped, or stained",
      "pool tile grout missing or damaged",
      "pool equipment clearly outdated or broken",
      "pool deck severely cracked or heaved",
      "pool light not functioning",
    ],
    crossSellFrom: ["pool_cleaning", "hardscaping"],
    description: "Pool replastering, tile repair, equipment replacement, and resurfacing",
  },
  {
    id: "water_filtration",
    name: "Water Filtration & Softeners",
    icon: "Filter",
    color: "text-blue-400",
    group: "Pool & Water",
    avgJobValue: 3500,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "hard water stains visible on fixtures, glass doors, or tile",
      "rust stains on sinks, tubs, or toilets",
      "older home with no visible water treatment equipment",
      "well water system visible",
    ],
    crossSellFrom: ["plumbing", "pool_cleaning"],
    description: "Whole-home water filtration, softeners, and reverse osmosis systems",
  },

  // ─── PEST & WILDLIFE ──────────────────────────────────────────────────────
  {
    id: "pest_control",
    name: "Pest Control",
    icon: "Bug",
    color: "text-red-600",
    group: "Pest & Wildlife",
    avgJobValue: 250,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "ant trails or ant mounds visible near foundation",
      "wasp or hornet nests visible under eaves or in trees",
      "spider webs concentrated around entry points",
      "wood damage or sawdust near wooden structures indicating termites",
      "rodent droppings or gnaw marks visible",
      "standing water near foundation (mosquito breeding)",
    ],
    crossSellFrom: ["lawn_care", "pet_waste_removal", "drainage"],
    description: "General pest control, termite treatment, mosquito control",
  },
  {
    id: "wildlife_removal",
    name: "Wildlife & Rodent Removal",
    icon: "Rat",
    color: "text-orange-700",
    group: "Pest & Wildlife",
    avgJobValue: 600,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visible entry points in soffits, fascia, or foundation",
      "chewed wood or damaged vents",
      "animal droppings near structure",
      "bird nests in gutters or vents",
    ],
    crossSellFrom: ["pest_control", "roofing", "handyman"],
    description: "Humane removal of raccoons, squirrels, birds, and rodents",
  },
  {
    id: "mosquito_control",
    name: "Mosquito & Tick Control",
    icon: "Zap",
    color: "text-red-500",
    group: "Pest & Wildlife",
    avgJobValue: 350,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "standing water in yard, birdbaths, or containers",
      "dense vegetation or overgrown areas near home",
      "wooded property line",
      "outdoor entertaining area without protection",
    ],
    crossSellFrom: ["lawn_care", "drainage", "pet_waste_removal"],
    description: "Seasonal mosquito and tick barrier treatments",
  },

  // ─── ROOFING & EXTERIOR ───────────────────────────────────────────────────
  {
    id: "roofing",
    name: "Roofing & Roof Repair",
    icon: "Home",
    color: "text-slate-600",
    group: "Roofing & Exterior",
    avgJobValue: 8000,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "missing, curled, or damaged shingles visible",
      "visible roof sagging or uneven roofline",
      "moss or algae growth on roof surface",
      "flashing around chimney or vents appears damaged or missing",
      "roof appears aged (granule loss, faded color)",
      "storm damage visible on roof",
    ],
    crossSellFrom: ["gutter_cleaning", "pest_control", "wildlife_removal", "storm_cleanup"],
    description: "Roof replacement, repair, inspections, and storm damage restoration",
  },
  {
    id: "gutter_cleaning",
    name: "Gutter Cleaning & Guards",
    icon: "ArrowDownToLine",
    color: "text-slate-500",
    group: "Roofing & Exterior",
    avgJobValue: 200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "gutters overflowing or sagging",
      "plant growth or debris visible in gutters",
      "gutters pulling away from fascia",
      "water stains on siding below gutters",
      "no downspout extensions visible",
    ],
    crossSellFrom: ["roofing", "lawn_care", "drainage", "pest_control"],
    description: "Gutter cleaning, repair, and gutter guard installation",
  },
  {
    id: "siding_repair",
    name: "Siding & Exterior Repair",
    icon: "PanelTop",
    color: "text-gray-600",
    group: "Roofing & Exterior",
    avgJobValue: 3500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracked, warped, or missing siding panels",
      "faded or peeling paint on siding",
      "visible wood rot on trim, fascia, or soffits",
      "gaps or holes in siding near foundation or corners",
      "mold or mildew staining on exterior walls",
    ],
    crossSellFrom: ["roofing", "painting_exterior", "pest_control", "pressure_washing"],
    description: "Vinyl, wood, fiber cement siding repair and replacement",
  },
  {
    id: "painting_exterior",
    name: "Exterior Painting",
    icon: "Paintbrush",
    color: "text-purple-500",
    group: "Roofing & Exterior",
    avgJobValue: 3500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "peeling, flaking, or faded exterior paint",
      "chalky or oxidized paint surface",
      "visible wood rot or bare wood on trim",
      "mismatched paint colors from previous repairs",
      "stucco cracks or discoloration",
    ],
    crossSellFrom: ["siding_repair", "pressure_washing", "handyman"],
    description: "Full exterior painting, staining, and finishing",
  },
  {
    id: "pressure_washing",
    name: "Pressure Washing",
    icon: "Droplet",
    color: "text-blue-400",
    group: "Roofing & Exterior",
    avgJobValue: 350,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "algae, mold, or mildew on driveway, walkway, or siding",
      "stained or dirty concrete driveway",
      "deck or patio with visible dirt and grime buildup",
      "fence with weathering or discoloration",
      "roof with moss or algae streaks",
    ],
    crossSellFrom: ["lawn_care", "pet_waste_removal", "pool_cleaning", "gutter_cleaning"],
    description: "Driveway, deck, siding, and roof soft washing",
  },
  {
    id: "window_cleaning",
    name: "Window Cleaning",
    icon: "AppWindow",
    color: "text-sky-400",
    group: "Roofing & Exterior",
    avgJobValue: 250,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visibly dirty or streaked windows",
      "hard water spots on window glass",
      "window screens with visible debris or damage",
    ],
    crossSellFrom: ["pressure_washing", "lawn_care", "pet_waste_removal"],
    description: "Interior and exterior window washing and screen cleaning",
  },
  {
    id: "window_repair",
    name: "Window & Door Repair",
    icon: "Square",
    color: "text-sky-600",
    group: "Roofing & Exterior",
    avgJobValue: 600,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracked or broken window glass",
      "foggy or condensation between double-pane windows",
      "window frame rotting or damaged",
      "door not closing properly or visibly warped",
      "missing or damaged window screens",
      "caulking around windows cracked or missing",
    ],
    crossSellFrom: ["pet_waste_removal", "handyman", "painting_exterior"],
    description: "Window replacement, door repair, and weatherproofing",
  },

  // ─── HVAC, PLUMBING & ELECTRICAL ─────────────────────────────────────────
  {
    id: "hvac",
    name: "HVAC & Air Conditioning",
    icon: "Thermometer",
    color: "text-orange-500",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 3000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "outdoor AC unit appears old, rusted, or damaged",
      "visible ice buildup on AC unit or lines",
      "AC unit surrounded by debris or vegetation",
      "multiple window AC units suggesting no central system",
      "condensate drain line visibly clogged or dripping",
    ],
    crossSellFrom: ["pest_control", "insulation", "electrical"],
    description: "AC installation, repair, maintenance, and duct cleaning",
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "Pipette",
    color: "text-blue-600",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 500,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "water stains on exterior walls or foundation",
      "visible pipe corrosion or leaking outdoor spigots",
      "hose bib dripping or damaged",
      "sewer cleanout cap missing or damaged",
      "outdoor water meter area with wet soil",
    ],
    crossSellFrom: ["drainage", "water_filtration", "handyman"],
    description: "Leak repair, pipe replacement, water heaters, and drain cleaning",
  },
  {
    id: "electrical",
    name: "Electrical Services",
    icon: "Zap",
    color: "text-yellow-600",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "outdoor electrical panel with visible damage or rust",
      "exposed wiring visible on exterior",
      "no outdoor GFCI outlets visible near pool or patio",
      "old or damaged outdoor light fixtures",
      "EV charger opportunity (newer vehicle visible in driveway)",
    ],
    crossSellFrom: ["outdoor_lighting", "hvac", "solar"],
    description: "Panel upgrades, outlet installation, lighting, and EV chargers",
  },
  {
    id: "solar",
    name: "Solar Panel Installation",
    icon: "Sun",
    color: "text-yellow-500",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 18000,
    platformFeeRate: 0.06,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "south-facing roof with no obstructions",
      "large unshaded roof area",
      "no existing solar panels visible",
      "newer home with good roof condition",
      "large property suggesting high energy usage",
    ],
    crossSellFrom: ["roofing", "electrical", "hvac"],
    description: "Residential solar panel installation and battery storage",
  },
  {
    id: "insulation",
    name: "Insulation & Energy Efficiency",
    icon: "Layers",
    color: "text-orange-400",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 2500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "attic vents showing signs of inadequate ventilation",
      "older home with original windows and no visible weatherstripping",
      "visible gaps around exterior penetrations",
      "crawl space vents open or damaged",
    ],
    crossSellFrom: ["hvac", "roofing", "handyman"],
    description: "Attic insulation, spray foam, and energy audits",
  },

  // ─── INTERIOR REMODELING ──────────────────────────────────────────────────
  {
    id: "kitchen_remodel",
    name: "Kitchen Remodeling",
    icon: "ChefHat",
    color: "text-red-500",
    group: "Interior Remodeling",
    avgJobValue: 25000,
    platformFeeRate: 0.07,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "kitchen visible through window with outdated cabinets",
      "older home suggesting original kitchen",
      "recent addition or renovation suggesting kitchen upgrade opportunity",
    ],
    crossSellFrom: ["plumbing", "electrical", "flooring", "painting_interior"],
    description: "Full kitchen renovation, cabinet replacement, countertops",
  },
  {
    id: "bathroom_remodel",
    name: "Bathroom Remodeling",
    icon: "Bath",
    color: "text-teal-500",
    group: "Interior Remodeling",
    avgJobValue: 12000,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "older home suggesting original bathrooms",
      "visible water damage or staining near bathroom windows",
      "recent plumbing work suggesting bathroom update opportunity",
    ],
    crossSellFrom: ["plumbing", "electrical", "flooring", "painting_interior"],
    description: "Bathroom renovation, tile work, vanity replacement",
  },
  {
    id: "flooring",
    name: "Flooring Installation",
    icon: "Grid3x3",
    color: "text-amber-600",
    group: "Interior Remodeling",
    avgJobValue: 4000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visible through door or window: worn, stained, or damaged flooring",
      "carpet visible through window in high-traffic area",
      "older home suggesting original flooring",
    ],
    crossSellFrom: ["painting_interior", "kitchen_remodel", "bathroom_remodel"],
    description: "Hardwood, LVP, tile, and carpet installation",
  },
  {
    id: "painting_interior",
    name: "Interior Painting",
    icon: "Paintbrush2",
    color: "text-purple-400",
    group: "Interior Remodeling",
    avgJobValue: 2500,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visible through window: faded or peeling interior walls",
      "recent renovation suggesting fresh paint needed",
      "new flooring or cabinets suggesting full interior refresh",
    ],
    crossSellFrom: ["flooring", "kitchen_remodel", "bathroom_remodel", "handyman"],
    description: "Interior painting, drywall repair, and wallpaper removal",
  },
  {
    id: "handyman",
    name: "Handyman Services",
    icon: "Hammer",
    color: "text-orange-600",
    group: "Interior Remodeling",
    avgJobValue: 350,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "damaged or rotting wood trim visible",
      "broken or missing shutters",
      "damaged steps or handrails",
      "cracked or damaged stucco or drywall visible",
      "general deferred maintenance visible on exterior",
      "mailbox damaged or leaning",
    ],
    crossSellFrom: ["pet_waste_removal", "lawn_care", "roofing", "fence_installation"],
    description: "General repairs, carpentry, drywall, and odd jobs",
  },
  {
    id: "garage_door",
    name: "Garage Door Repair & Installation",
    icon: "DoorOpen",
    color: "text-gray-500",
    group: "Interior Remodeling",
    avgJobValue: 1200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "garage door panels dented or damaged",
      "garage door visibly misaligned or off track",
      "old wooden garage door suggesting upgrade opportunity",
      "no smart garage door opener visible",
    ],
    crossSellFrom: ["handyman", "electrical", "painting_exterior"],
    description: "Garage door installation, repair, and smart opener upgrades",
  },
  {
    id: "foundation_repair",
    name: "Foundation Repair",
    icon: "Building",
    color: "text-stone-700",
    group: "Interior Remodeling",
    avgJobValue: 8000,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "visible cracks in foundation or exterior brick",
      "doors or windows visibly sticking or misaligned",
      "soil pulling away from foundation",
      "stair-step cracks in brick mortar",
      "bowing or bulging walls",
    ],
    crossSellFrom: ["drainage", "plumbing", "pest_control"],
    description: "Pier installation, crack repair, and waterproofing",
  },

  // ─── CLEANING & MAINTENANCE ───────────────────────────────────────────────
  {
    id: "house_cleaning",
    name: "House Cleaning",
    icon: "Sparkles",
    color: "text-pink-400",
    group: "Cleaning & Maintenance",
    avgJobValue: 180,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "busy household with multiple vehicles suggesting time-poor homeowners",
      "large home suggesting high cleaning demand",
      "recent renovation suggesting post-construction clean needed",
    ],
    crossSellFrom: ["pet_waste_removal", "lawn_care", "window_cleaning"],
    description: "Regular house cleaning, deep cleaning, and move-in/out cleaning",
  },
  {
    id: "carpet_cleaning",
    name: "Carpet & Upholstery Cleaning",
    icon: "Sofa",
    color: "text-pink-600",
    group: "Cleaning & Maintenance",
    avgJobValue: 300,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "carpet visible through window or door",
      "pets visible in home suggesting pet stain treatment",
      "older home with original carpet",
    ],
    crossSellFrom: ["pet_waste_removal", "house_cleaning", "flooring"],
    description: "Steam cleaning for carpets, rugs, and upholstery",
  },
  {
    id: "junk_removal",
    name: "Junk Removal & Hauling",
    icon: "Trash2",
    color: "text-gray-500",
    group: "Cleaning & Maintenance",
    avgJobValue: 400,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visible debris, old furniture, or junk in yard",
      "construction debris from renovation project",
      "old appliances or equipment visible outside",
      "overfull garage visible through open door",
    ],
    crossSellFrom: ["landscaping", "handyman", "storm_cleanup"],
    description: "Full-service junk removal, estate cleanouts, and debris hauling",
  },
  {
    id: "storm_cleanup",
    name: "Storm Cleanup & Restoration",
    icon: "CloudLightning",
    color: "text-indigo-500",
    group: "Cleaning & Maintenance",
    avgJobValue: 2000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "fallen branches or debris in yard",
      "storm damage to fence, roof, or siding",
      "standing water from recent storm",
      "damaged or missing shingles after storm",
    ],
    crossSellFrom: ["tree_service", "roofing", "fence_installation", "drainage"],
    description: "Emergency storm debris removal and property restoration",
  },
  {
    id: "chimney_cleaning",
    name: "Chimney Cleaning & Repair",
    icon: "Flame",
    color: "text-red-700",
    group: "Cleaning & Maintenance",
    avgJobValue: 350,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "chimney visible on roof",
      "chimney cap missing or damaged",
      "mortar crumbling on chimney",
      "chimney flashing damaged or missing",
      "staining or efflorescence on chimney exterior",
    ],
    crossSellFrom: ["roofing", "pest_control", "wildlife_removal"],
    description: "Chimney sweeping, cap installation, and masonry repair",
  },

  // ─── ANIMALS & PETS ───────────────────────────────────────────────────────
  {
    id: "dog_walking",
    name: "Dog Walking & Pet Sitting",
    icon: "PawPrint",
    color: "text-amber-500",
    group: "Animals & Pets",
    avgJobValue: 200,
    platformFeeRate: 0.15,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dog visible in yard or through window",
      "dog door installed in door or wall",
      "dog kennel or crate visible",
      "multiple dogs visible",
    ],
    crossSellFrom: ["pet_waste_removal", "veterinary", "grooming"],
    description: "Dog walking, pet sitting, and doggy daycare",
  },
  {
    id: "grooming",
    name: "Pet Grooming",
    icon: "Scissors",
    color: "text-pink-500",
    group: "Animals & Pets",
    avgJobValue: 80,
    platformFeeRate: 0.15,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dog visible with long or matted coat",
      "multiple dogs visible",
      "dog door or kennel visible",
    ],
    crossSellFrom: ["pet_waste_removal", "dog_walking", "veterinary"],
    description: "Mobile and in-home pet grooming services",
  },
  {
    id: "veterinary",
    name: "Veterinary & Pet Health",
    icon: "Heart",
    color: "text-red-400",
    group: "Animals & Pets",
    avgJobValue: 200,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dog visible in yard",
      "dog door or kennel visible",
      "multiple pets visible",
    ],
    crossSellFrom: ["pet_waste_removal", "dog_walking", "grooming"],
    description: "Mobile vet services, vaccinations, and wellness checks",
  },

  // ─── SECURITY & SMART HOME ────────────────────────────────────────────────
  {
    id: "security_systems",
    name: "Home Security Systems",
    icon: "Shield",
    color: "text-slate-700",
    group: "Security & Smart Home",
    avgJobValue: 1500,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "no visible security cameras on exterior",
      "no visible doorbell camera",
      "dark areas around property with no lighting",
      "large property with multiple entry points",
      "no visible alarm system signage",
    ],
    crossSellFrom: ["outdoor_lighting", "electrical", "smart_home"],
    description: "Camera systems, alarm installation, and smart locks",
  },
  {
    id: "smart_home",
    name: "Smart Home Installation",
    icon: "Wifi",
    color: "text-indigo-400",
    group: "Security & Smart Home",
    avgJobValue: 1200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "no visible smart doorbell or camera",
      "older home with no visible smart devices",
      "new construction or recent renovation",
      "EV charger visible suggesting tech-forward homeowner",
    ],
    crossSellFrom: ["electrical", "security_systems", "hvac"],
    description: "Smart thermostats, lighting, locks, and whole-home automation",
  },

  // ─── SPECIALTY SERVICES ───────────────────────────────────────────────────
  {
    id: "holiday_lighting",
    name: "Holiday & Event Lighting",
    icon: "Star",
    color: "text-yellow-400",
    group: "Specialty Services",
    avgJobValue: 800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "large home with prominent roofline",
      "established landscape with trees suitable for lighting",
      "upscale neighborhood visible in background",
    ],
    crossSellFrom: ["outdoor_lighting", "landscaping", "electrical"],
    description: "Professional holiday light installation and removal",
  },
  {
    id: "dumpster_rental",
    name: "Dumpster Rental",
    icon: "Container",
    color: "text-gray-600",
    group: "Specialty Services",
    avgJobValue: 450,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "active renovation or construction visible",
      "large debris pile in yard",
      "roofing or siding project in progress",
    ],
    crossSellFrom: ["roofing", "landscaping", "junk_removal", "kitchen_remodel"],
    description: "Residential dumpster rental for renovations and cleanouts",
  },
  {
    id: "moving_services",
    name: "Moving Services",
    icon: "Truck",
    color: "text-blue-500",
    group: "Specialty Services",
    avgJobValue: 1500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "moving truck or boxes visible on property",
      "for sale sign visible near property",
      "empty or partially furnished home visible through window",
    ],
    crossSellFrom: ["house_cleaning", "junk_removal", "handyman"],
    description: "Local and long-distance moving, packing, and storage",
  },
  {
    id: "home_inspection",
    name: "Home Inspection",
    icon: "ClipboardCheck",
    color: "text-teal-600",
    group: "Specialty Services",
    avgJobValue: 400,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "for sale sign visible",
      "new construction visible",
      "visible deferred maintenance suggesting pre-listing inspection",
    ],
    crossSellFrom: ["roofing", "foundation_repair", "pest_control", "hvac"],
    description: "Pre-purchase, pre-listing, and new construction inspections",
  },
  {
    id: "concrete_repair",
    name: "Concrete & Masonry",
    icon: "Layers",
    color: "text-stone-500",
    group: "Specialty Services",
    avgJobValue: 2000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracked or heaved driveway concrete",
      "cracked sidewalk or walkway",
      "spalling or pitted concrete surfaces",
      "brick mortar crumbling or missing",
      "retaining wall cracking or leaning",
    ],
    crossSellFrom: ["drainage", "foundation_repair", "hardscaping"],
    description: "Driveway repair, sidewalk leveling, and masonry restoration",
  },
  {
    id: "deck_repair",
    name: "Deck Building & Repair",
    icon: "LayoutGrid",
    color: "text-amber-700",
    group: "Specialty Services",
    avgJobValue: 6000,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "deck boards visibly rotting, warped, or discolored",
      "deck railing loose or missing balusters",
      "deck with peeling stain or paint",
      "no deck on home with large backyard",
      "deck posts showing signs of rot at base",
    ],
    crossSellFrom: ["hardscaping", "painting_exterior", "pressure_washing", "outdoor_lighting"],
    description: "New deck construction, repair, staining, and railing replacement",
  },
  {
    id: "generator_installation",
    name: "Generator Installation",
    icon: "Battery",
    color: "text-yellow-700",
    group: "Specialty Services",
    avgJobValue: 8000,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "no visible standby generator on property",
      "large home suggesting high power dependency",
      "home office or medical equipment visible",
      "area prone to power outages (rural or storm-prone)",
    ],
    crossSellFrom: ["electrical", "hvac", "solar"],
    description: "Whole-home standby generator installation and maintenance",
  },
  // ─── INTERIOR REMODELING (additions) ──────────────────────────────────────
  {
    id: "cabinet_refinishing",
    name: "Cabinet Refinishing & Refacing",
    icon: "Package",
    color: "text-amber-700",
    group: "Interior Remodeling",
    avgJobValue: 3200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cabinet doors with peeling, chipped, or faded paint or stain",
      "outdated cabinet hardware (hinges, pulls, knobs)",
      "cabinet doors that are warped, cracked, or misaligned",
      "laminate cabinet surfaces that are bubbling or delaminating",
      "dark or dated wood cabinets in kitchen or bathroom",
    ],
    crossSellFrom: ["kitchen_remodel", "bathroom_remodel", "painting_interior", "handyman"],
    description: "Cabinet painting, staining, refacing, and hardware upgrades",
  },
  {
    id: "closet_organization",
    name: "Closet & Storage Organization",
    icon: "LayoutGrid",
    color: "text-purple-600",
    group: "Interior Remodeling",
    avgJobValue: 1800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "overflowing or disorganized closet with no built-in shelving",
      "wire shelving that is sagging or pulling from wall",
      "garage with no wall storage system — tools and boxes on floor",
      "laundry room with no shelving or folding surface",
      "pantry with no organizational system",
    ],
    crossSellFrom: ["handyman", "garage_door", "flooring", "painting_interior"],
    description: "Custom closet systems, garage storage, pantry organization",
  },
  {
    id: "tile_installation",
    name: "Tile Installation & Repair",
    icon: "Grid3x3",
    color: "text-slate-600",
    group: "Interior Remodeling",
    avgJobValue: 2200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracked, chipped, or missing floor or wall tiles",
      "grout lines that are discolored, crumbling, or missing",
      "bathroom tile that shows water staining or mold around grout",
      "outdated tile pattern in kitchen backsplash area",
      "uneven or lippage issues visible in tile floor",
    ],
    crossSellFrom: ["bathroom_remodel", "kitchen_remodel", "flooring", "plumbing"],
    description: "Floor tile, wall tile, backsplash, and grout repair",
  },
  {
    id: "drywall_repair",
    name: "Drywall Repair & Finishing",
    icon: "Square",
    color: "text-gray-600",
    group: "Interior Remodeling",
    avgJobValue: 650,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "holes, dents, or cracks in interior walls or ceilings",
      "water stain rings or bubbling paint on ceiling indicating past leak",
      "texture mismatch where a patch was previously applied",
      "nail pops or screw heads visible through paint",
      "corner bead damage or crumbling at wall corners",
    ],
    crossSellFrom: ["painting_interior", "plumbing", "roofing", "handyman"],
    description: "Hole patching, water damage repair, texture matching",
  },
  // ─── ROOFING & EXTERIOR (additions) ──────────────────────────────────────
  {
    id: "stucco_repair",
    name: "Stucco & Exterior Plaster",
    icon: "Layers",
    color: "text-orange-600",
    group: "Roofing & Exterior",
    avgJobValue: 1800,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "cracks in exterior stucco — hairline or larger",
      "stucco that is bubbling, blistering, or separating from substrate",
      "discoloration or efflorescence (white salt deposits) on stucco",
      "impact damage or holes in stucco surface",
      "stucco around windows or doors showing water infiltration signs",
    ],
    crossSellFrom: ["painting_exterior", "siding_repair", "roofing", "foundation_repair"],
    description: "Stucco crack repair, patching, and full re-coat",
  },
  {
    id: "awning_installation",
    name: "Awnings & Shade Structures",
    icon: "Umbrella",
    color: "text-yellow-600",
    group: "Roofing & Exterior",
    avgJobValue: 2800,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "south or west-facing windows with no sun protection",
      "patio or deck with no overhead shade coverage",
      "faded or torn existing awning fabric",
      "awning frame that is bent, rusted, or pulling from wall",
      "pergola structure with no shade material installed",
    ],
    crossSellFrom: ["deck_repair", "hardscaping", "outdoor_lighting", "painting_exterior"],
    description: "Retractable awnings, pergola covers, shade sails",
  },
  // ─── HVAC, PLUMBING & ELECTRICAL (additions) ─────────────────────────────
  {
    id: "water_heater",
    name: "Water Heater Installation & Repair",
    icon: "Flame",
    color: "text-red-600",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 1400,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "water heater unit showing rust or corrosion on tank or connections",
      "water heater that is 10+ years old (visible manufacture date sticker)",
      "water staining or mineral deposits on floor around water heater",
      "expansion tank missing or corroded on newer pressure-regulated systems",
      "gas line connections showing signs of wear or improper installation",
    ],
    crossSellFrom: ["plumbing", "hvac", "insulation", "solar"],
    description: "Tank and tankless water heater install, repair, and replacement",
  },
  {
    id: "ev_charging",
    name: "EV Charging Station Installation",
    icon: "Zap",
    color: "text-blue-500",
    group: "HVAC, Plumbing & Electrical",
    avgJobValue: 1800,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "electric vehicle visible in garage or driveway",
      "no EV charger outlet visible in garage",
      "standard 120V outlet near garage parking area (upgrade opportunity)",
      "electrical panel with available breaker slots visible",
      "new construction or recently renovated garage",
    ],
    crossSellFrom: ["electrical", "solar", "garage_door", "smart_home"],
    description: "Level 2 home EV charger installation and panel upgrades",
  },
  // ─── CLEANING & MAINTENANCE (additions) ──────────────────────────────────
  {
    id: "air_duct_cleaning",
    name: "Air Duct & Dryer Vent Cleaning",
    icon: "Wind",
    color: "text-sky-500",
    group: "Cleaning & Maintenance",
    avgJobValue: 450,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "visible dust buildup on supply or return air vents",
      "dryer vent cover on exterior showing lint accumulation",
      "HVAC system that appears to be 5+ years old without visible maintenance",
      "musty odor indicators — air fresheners placed near vents",
      "pet hair visible throughout home suggesting high dander load",
    ],
    crossSellFrom: ["hvac", "house_cleaning", "carpet_cleaning", "pest_control"],
    description: "HVAC duct cleaning, dryer vent cleaning, and sanitization",
  },
  {
    id: "power_washing_concrete",
    name: "Concrete & Driveway Cleaning",
    icon: "Droplets",
    color: "text-cyan-600",
    group: "Cleaning & Maintenance",
    avgJobValue: 350,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "driveway with oil stains, tire marks, or heavy discoloration",
      "concrete walkway with moss, algae, or mildew growth",
      "pool deck with visible grime or slip-hazard algae",
      "patio pavers with weed growth in joints or heavy staining",
      "brick or stone surfaces with efflorescence or biological growth",
    ],
    crossSellFrom: ["pressure_washing", "concrete_repair", "hardscaping", "deck_repair"],
    description: "High-pressure cleaning for driveways, patios, and concrete",
  },
  // ─── SPECIALTY SERVICES (additions) ──────────────────────────────────────
  {
    id: "epoxy_flooring",
    name: "Epoxy & Garage Floor Coating",
    icon: "PaintBucket",
    color: "text-indigo-600",
    group: "Specialty Services",
    avgJobValue: 2200,
    platformFeeRate: 0.12,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "bare concrete garage floor with oil stains or pitting",
      "peeling or flaking existing garage floor coating",
      "basement concrete floor with no finishing",
      "workshop or utility room with unfinished concrete",
      "commercial-style space with polished concrete look",
    ],
    crossSellFrom: ["garage_door", "closet_organization", "concrete_repair", "flooring"],
    description: "Epoxy floor coatings, polyaspartic coatings, and decorative concrete",
  },
  {
    id: "radon_testing",
    name: "Radon Testing & Mitigation",
    icon: "AlertTriangle",
    color: "text-red-500",
    group: "Specialty Services",
    avgJobValue: 1200,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "basement or below-grade living space visible",
      "home in geographic area known for radon (Midwest, Mountain states)",
      "older home without visible radon mitigation pipe on exterior",
      "crawl space with no vapor barrier visible",
      "home inspection report visible with radon concerns noted",
    ],
    crossSellFrom: ["home_inspection", "foundation_repair", "insulation", "hvac"],
    description: "Radon gas testing, mitigation system installation",
  },
  {
    id: "mold_remediation",
    name: "Mold Testing & Remediation",
    icon: "Shield",
    color: "text-green-800",
    group: "Specialty Services",
    avgJobValue: 3500,
    platformFeeRate: 0.10,
    referralCommissionRate: 0.05,
    aiDetectionCues: [
      "dark spots or discoloration on walls, ceilings, or grout",
      "water staining around windows, doors, or roof penetrations",
      "bathroom or basement with poor ventilation and moisture signs",
      "visible condensation on windows or walls",
      "musty or damp smell indicators near HVAC or basement",
    ],
    crossSellFrom: ["roofing", "plumbing", "hvac", "insulation", "drywall_repair"],
    description: "Mold inspection, testing, and full remediation services",
  },
  {
    id: "fire_restoration",
    name: "Fire & Smoke Damage Restoration",
    icon: "Flame",
    color: "text-orange-700",
    group: "Specialty Services",
    avgJobValue: 8500,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "visible char marks or soot on walls, ceilings, or surfaces",
      "smoke staining around electrical outlets or fixtures",
      "fire-damaged exterior siding, fascia, or roofline",
      "melted or warped materials visible in kitchen or utility areas",
      "restoration company signage or equipment visible at property",
    ],
    crossSellFrom: ["roofing", "painting_interior", "drywall_repair", "flooring", "hvac"],
    description: "Fire damage cleanup, smoke odor removal, and structural restoration",
  },
  {
    id: "water_damage_restoration",
    name: "Water Damage Restoration",
    icon: "Droplets",
    color: "text-blue-700",
    group: "Specialty Services",
    avgJobValue: 5500,
    platformFeeRate: 0.08,
    referralCommissionRate: 0.04,
    aiDetectionCues: [
      "water staining or tide marks on walls or baseboards",
      "buckled, warped, or cupping hardwood floors",
      "ceiling tiles or drywall with active or dried water damage",
      "wet or damp carpet with visible discoloration",
      "industrial drying equipment or dehumidifiers visible",
    ],
    crossSellFrom: ["plumbing", "roofing", "flooring", "drywall_repair", "mold_remediation"],
    description: "Emergency water extraction, drying, and structural restoration",
  },
];

export const SERVICE_GROUPS = [
  "Lawn & Outdoor",
  "Pool & Water",
  "Pest & Wildlife",
  "Roofing & Exterior",
  "HVAC, Plumbing & Electrical",
  "Interior Remodeling",
  "Cleaning & Maintenance",
  "Animals & Pets",
  "Security & Smart Home",
  "Specialty Services",
];

export function getCategoryById(id: string): ServiceCategory | undefined {
  return SERVICE_CATEGORIES.find(c => c.id === id);
}

export function getCategoriesByGroup(group: string): ServiceCategory[] {
  return SERVICE_CATEGORIES.filter(c => c.group === group);
}

export function getCrossellTargets(categoryId: string): ServiceCategory[] {
  const cat = getCategoryById(categoryId);
  if (!cat) return [];
  return cat.crossSellFrom.map(id => getCategoryById(id)).filter(Boolean) as ServiceCategory[];
}

export function buildAiPromptForCategory(category: ServiceCategory): string {
  return `You are analyzing a job completion photo for a ${category.name} service call. 
Look specifically for these visual indicators that suggest a need for this service:
${category.aiDetectionCues.map((cue, i) => `${i + 1}. ${cue}`).join('\n')}

If you detect any of these indicators, report them with a confidence score (0.0-1.0) and estimated job value.`;
}

export function buildMasterAiPrompt(categories: ServiceCategory[]): string {
  return `You are an AI assistant for ProLnk, an intelligent home service referral network. 
Analyze this job completion photo and identify ALL visible opportunities for home services.

For each opportunity detected, provide:
- opportunityType: one of [${categories.map(c => c.id).join(', ')}]
- description: specific description of what you see
- confidence: 0.0 to 1.0
- estimatedValue: estimated job value in USD
- urgency: "immediate" | "soon" | "future"

Visual indicators to look for by category:
${categories.map(c => `
[${c.id}] ${c.name}:
${c.aiDetectionCues.map(cue => `  - ${cue}`).join('\n')}`).join('\n')}

Return a JSON array of opportunities. If no opportunities are detected, return an empty array.
Be specific about what you see — do not hallucinate or guess. Only report what is visually evident.`;
}
