import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import HomeownerLayout from "@/components/HomeownerLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Home, TrendingUp, Loader2, DollarSign, Wrench, Download } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

export default function HomeValueImpact() {
  const { data, isLoading } = trpc.homeownerExtras.getHomeValueImpact.useQuery();

  if (isLoading) return (
    <div className="flex items-center justify-center h-64"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground" /></div>
  );

  const { improvements = [], estimatedValueAdded = 0, propertyValue, address } = data ?? {};

  const handleDownload = () => {
    const date = new Date().toLocaleDateString();
    const html = `
<!DOCTYPE html><html><head><title>Home Value Report — TrustyPro</title>
<style>body{font-family:sans-serif;max-width:700px;margin:40px auto;color:#1a1a1a}h1{color:#0A1628}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #e5e7eb}th{background:#f9fafb;font-size:12px;text-transform:uppercase;letter-spacing:.05em}.total{font-weight:700;color:#059669}.footer{margin-top:40px;font-size:12px;color:#9ca3af}</style>
</head><body>
<h1>Home Value Impact Report</h1>
<p>Property: ${address ?? "Your Home"} &nbsp;|&nbsp; Generated: ${date}</p>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:24px 0">
<div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;text-align:center">
  <p style="font-size:12px;color:#6b7280;margin:0 0 4px">Estimated Property Value</p>
  <p style="font-size:28px;font-weight:700;margin:0">${propertyValue ? `$${Number(propertyValue).toLocaleString()}` : "—"}</p>
</div>
<div style="border:1px solid #d1fae5;border-radius:8px;padding:16px;text-align:center;background:#ecfdf5">
  <p style="font-size:12px;color:#6b7280;margin:0 0 4px">Total Value Added</p>
  <p style="font-size:28px;font-weight:700;color:#059669;margin:0">+$${estimatedValueAdded.toLocaleString()}</p>
</div></div>
${improvements.length > 0 ? `
<h2>Logged Improvements</h2>
<table><thead><tr><th>Improvement</th><th>Date</th><th>Cost</th><th>Est. Value Added</th></tr></thead><tbody>
${improvements.map((imp: any) => {
  const cost = Number(imp.cost ?? 0);
  return `<tr><td>${imp.title ?? imp.category}</td><td>${imp.completedAt ? new Date(imp.completedAt).toLocaleDateString() : "—"}</td><td>$${cost.toLocaleString()}</td><td class="total">+$${Math.round(cost * 0.65).toLocaleString()}</td></tr>`;
}).join("")}
</tbody></table>` : ""}
<p class="footer">Generated by TrustyPro — trustypro.io | Data is an estimate. Consult a licensed appraiser for formal valuation.</p>
</body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `home-value-report-${new Date().toISOString().slice(0,10)}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <HomeownerLayout>
    <div className="max-w-2xl mx-auto space-y-6 p-4">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">Home Value Impact</h1>
          <p className="text-muted-foreground mt-1">See how your improvements affect your home's estimated value.</p>
        </div>
        <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5 shrink-0">
          <Download className="h-4 w-4" /> Download Report
        </Button>
      </div>

      {address && <p className="text-sm text-muted-foreground flex items-center gap-1"><Home className="h-3.5 w-3.5" />{address}</p>}

      <div className="grid grid-cols-2 gap-4">
        {propertyValue && (
          <Card>
            <CardContent className="pt-4 text-center">
              <p className="text-xs text-muted-foreground mb-1">Estimated Value</p>
              <p className="text-2xl font-bold">${Number(propertyValue).toLocaleString()}</p>
            </CardContent>
          </Card>
        )}
        <Card className="border-green-200 bg-green-50 dark:bg-green-950/20">
          <CardContent className="pt-4 text-center">
            <p className="text-xs text-muted-foreground mb-1">Value Added</p>
            <p className="text-2xl font-bold text-green-700 dark:text-green-400">+${estimatedValueAdded.toLocaleString()}</p>
          </CardContent>
        </Card>
      </div>

      {improvements.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <TrendingUp className="h-10 w-10 mx-auto text-muted-foreground mb-3" />
            <p className="font-medium">No improvements logged yet</p>
            <p className="text-sm text-muted-foreground mt-1">Log your home improvements to see their estimated impact on value.</p>
            <Link href="/my-home/projects">
              <Button className="mt-4">Log an Improvement</Button>
            </Link>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          <h2 className="font-semibold text-sm">Logged Improvements</h2>
          {improvements.map((imp: any) => {
            const cost = Number(imp.cost ?? 0);
            const roi = 0.65;
            const valueAdded = Math.round(cost * roi);
            return (
              <Card key={imp.id}>
                <CardContent className="pt-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-medium text-sm">{imp.title ?? imp.category}</p>
                      <p className="text-xs text-muted-foreground">{imp.completedAt ? new Date(imp.completedAt).toLocaleDateString() : "Date unknown"}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-semibold flex items-center gap-0.5"><DollarSign className="h-3.5 w-3.5" />{cost.toLocaleString()}</p>
                      <p className="text-xs text-green-600">+${valueAdded.toLocaleString()} est. value</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
    </HomeownerLayout>
  );
}
