import { useState } from 'react';

const systems = ['HVAC', 'Plumbing', 'Electrical', 'Roofing', 'Foundation', 'Pest Control'];

const systemIcons: Record<string, string> = {
  HVAC: '❄️',
  Plumbing: '💧',
  Electrical: '⚡',
  Roofing: '🏠',
  Foundation: '🏗️',
  'Pest Control': '🐛',
};

type SituationMap = Record<string, { guidance: string; urgency: string; cost: string }>;
type SystemData = { overview: string; situations: string[]; guidance: SituationMap };

const masterGuide: Record<string, SystemData> = {
  HVAC: {
    overview: 'DFW HVAC systems work harder than almost anywhere in the country — 8+ month cooling seasons, 140°F attic temperatures, and occasional hard freezes. Expected system life: 12–18 years. Key metric: SEER2 rating (higher = more efficient). In DFW, humidity control is as important as temperature control.',
    situations: ['System is 10+ years old, bills rising', 'Uneven temps room to room', 'Humidity feels wrong indoors', 'System short-cycles (runs briefly, stops)', 'Strange noises or smells', 'Post-freeze failure or no heat'],
    guidance: {
      'System is 10+ years old, bills rising': { guidance: 'At 10 years in DFW, efficiency has degraded 20–40%. Have system tested: refrigerant charge, capacitors, coil cleanliness, duct leakage. If repair cost exceeds 50% of replacement, replace. Prioritize inverter (variable-speed) system for DFW climate — 30–40% efficiency gain over single-stage.', urgency: 'Plan proactively — don\’t wait for failure in July.', cost: 'Tune-up: $150–$300. Replacement: $5,500–$14,000 depending on size and type.' },
      'Uneven temps room to room': { guidance: 'Three causes in DFW: (1) Duct leakage — 25–40% of conditioned air escapes into attic. Get duct test ($150–$300). (2) Insulation inadequate — DFW needs R-60 in attics. (3) System oversized — single-stage systems blast then stop, creating hot spots. Fix in order: duct sealing → insulation → system right-sizing if replacing.', urgency: 'Comfort issue, not emergency. Address before next summer.', cost: 'Duct sealing: $500–$1,800. Insulation: $1,500–$3,500. System right-sizing: part of replacement quote.' },
      'Humidity feels wrong indoors': { guidance: 'DFW targets 45–50% indoor RH. Below 40%: dry sinuses, static, wood shrinkage — check humidifier function or add whole-home humidifier ($600–$1,200). Above 55%: mold risk, musty smell — check drain pan, coil, and consider whole-home dehumidifier ($1,500–$2,500). Inverter systems control humidity far better than single-stage — strongly consider at next replacement.', urgency: 'High RH (>60%) requires prompt attention — mold grows fast in DFW summer.', cost: 'Whole-home dehumidifier: $1,500–$2,500 installed.' },
      'System short-cycles (runs briefly, stops)': { guidance: 'Most common cause in DFW: system is oversized. A system sized for a leaky old house will be oversized after air sealing and insulation. Also check: dirty evaporator coil, low refrigerant, stuck contactor. If system is correctly sized and still short-cycles, check thermostat location (avoid direct sunlight or supply air paths).', urgency: 'Increases wear and humidity problems. Address within 2–4 weeks.', cost: 'Diagnosis: $150–$250. Coil clean: $200–$400. Refrigerant charge: $200–$500.' },
      'Strange noises or smells': { guidance: 'DFW-specific: burning smell at first fall heating use is normal (dust on elements). Persist beyond first day: check for animal nesting in outdoor unit or ductwork (common in DFW). Squealing: bearings failing. Banging: loose blower wheel or compressor issue. Musty smell: mold on evaporator coil — UV air purifier recommended. Rotten egg smell: gas leak — evacuate and call gas company immediately.', urgency: 'Rotten egg = emergency. Other smells/noises: service within 1 week.', cost: 'Service call: $150–$300. UV purifier: $600–$1,200. Blower wheel: $200–$500.' },
      'Post-freeze failure or no heat': { guidance: 'Post-DFW-freeze checklist: (1) Check breakers. (2) Verify thermostat is set to heat mode. (3) Check outdoor unit — if iced, run defrost mode. (4) Check emergency heat switch on heat pump. If gas furnace: check pilot light, gas valve, igniter. If all else fails, call emergency HVAC service. Note: after 2021 freeze, emergency service demand was 6–8 week backlog — have a backup plan (space heaters, hotel, family).', urgency: 'Emergency — address immediately in freezing conditions.', cost: 'Emergency service: $300–$600 after-hours. Igniter replacement: $200–$400.' },
  },
  Plumbing: {
    overview: 'DFW plumbing faces unique challenges: expansive clay soil causes pipe movement and slab leaks, hard water (300–500 ppm) damages water heaters and fixtures, and freeze events (rare but severe) cause burst pipes. Most DFW homes have copper or CPVC supply lines. Slab foundations are standard — all plumbing runs under concrete.',
    situations: ['Water heater 10+ years old', 'Low water pressure throughout home', 'Slab leak suspected (hot floor, high water bill)', 'Hard water damage to fixtures', 'Post-freeze pipe burst', 'Slow drains throughout home'],
    guidance: {
      'Water heater 10+ years old': { guidance: 'DFW hard water destroys water heaters faster than average — expect 10–13 years on tank heaters. At 10 years: flush tank to remove sediment ($50–$100 DIY, or have plumber do during service visit). Assess anode rod. Budget for replacement. Upgrade options: tankless ($2,500–$4,500 installed — requires gas line upgrade or 240V), heat pump water heater ($1,200–$2,000 — most efficient, ideal if going all-electric).', urgency: 'Proactive — budget and plan before failure. Emergency replacement is 2x the cost.', cost: 'Tank replacement: $900–$1,400. Tankless: $2,500–$4,500. Heat pump: $1,200–$2,000.' },
      'Low water pressure throughout home': { guidance: 'In DFW: (1) Check pressure reducing valve (PRV) — most DFW homes have one. PRVs fail at 7–10 years; replacement is $250–$500. (2) Check main shutoff valve for partial closure. (3) Check water softener if installed — resin bed can restrict flow. (4) Corroded galvanized pipes in older homes — full repipe in copper or PEX ($8,000–$18,000). (5) Municipality supply pressure issue — check neighbors.', urgency: 'Not emergency unless total loss. Diagnose within 2 weeks.', cost: 'PRV replacement: $250–$500. Repipe: $8,000–$18,000.' },
      'Slab leak suspected (hot floor, high water bill)': { guidance: 'DFW clay soil movement causes slab leaks — a major regional issue. Signs: warm spot on floor, sound of running water with all fixtures off, unexplained bill increase, damp drywall at base. Confirm with electronic leak detection ($200–$400). Repair options: direct access through slab ($1,500–$4,000), epoxy pipe lining ($3,000–$7,000), or full reroute through walls/attic ($5,000–$12,000). Get 2–3 quotes. Check homeowner\’s insurance — slab leaks may be covered.', urgency: 'High — active water leak causes mold and structural damage quickly.', cost: 'Detection: $200–$400. Repair: $1,500–$12,000 depending on method.' },
      'Hard water damage to fixtures': { guidance: 'DFW water hardness of 300–500 ppm causes scale buildup in water heaters (reducing efficiency 25–40%), faucet aerators, showerheads, and appliances. Solutions: whole-home water softener ($1,200–$3,000 installed) is the most effective. Salt-free conditioners ($600–$1,500) reduce scale without sodium. Minimum: descale water heater annually, replace aerators every 2 years. Without treatment, water heater life drops from 12+ to 8 years.', urgency: 'Ongoing maintenance issue. Install softener proactively.', cost: 'Water softener: $1,200–$3,000 installed. Annual maintenance: $100–$200.' },
      'Post-freeze pipe burst': { guidance: 'DFW freeze pipe burst protocol: (1) Locate and shut main water valve immediately. (2) Open faucets to relieve pressure. (3) Document damage for insurance — photograph everything before cleanup. (4) Contact plumber and restoration company simultaneously — restoration must begin within 24–48 hours to prevent mold. (5) In future: insulate pipes in exterior walls and attic, know main shutoff location, drip faucets during freeze warnings.', urgency: 'Emergency — act within hours.', cost: 'Pipe repair: $400–$2,000. Water damage restoration: $3,000–$20,000+ depending on extent.' },
      'Slow drains throughout home': { guidance: 'Multiple slow drains = main line issue in DFW. Clay soil intrusion through older cast iron pipes is common in pre-1980 DFW homes. Root intrusion is also common — DFW\’s clay soil stress causes roots to seek pipe water. Get camera inspection ($200–$400) before any work. Options: hydro-jet cleaning ($400–$800), root removal ($500–$1,200), or pipe lining/replacement if severely compromised ($5,000–$15,000).', urgency: 'Address within 2 weeks before backup occurs.', cost: 'Camera: $200–$400. Cleaning: $400–$800. Line repair/replace: $5,000–$15,000.' },
    },
  },
  Electrical: {
    overview: 'DFW electrical systems vary widely by home age. Pre-1960 homes may have aluminum wiring or fuse boxes. 1960s–80s homes typically have 100–150A service. Modern homes need 200A+ for HVAC, EV charging, and whole-home loads. ONCOR serves most DFW; Brazos Electric and others serve some areas. TDU (transmission and distribution utility) charges are separate from retail electric provider.',
    situations: ['Breakers tripping frequently', 'Planning EV charger installation', 'Old fuse box or 100A service', 'Planning addition or major renovation', 'Outlets sparking or warm to touch', 'Generator or battery backup planning'],
    guidance: {
      'Breakers tripping frequently': { guidance: 'DFW summer HVAC load is the most common culprit — a 5-ton system draws 40–50A startup current. If HVAC breaker trips: check for dirty filter (airflow restriction increases amp draw), check capacitor (failing capacitors cause overcurrent), or system may be oversized. Non-HVAC breakers: calculate load (NEC allows 80% of breaker rating for continuous loads). Kitchen circuits are frequently overloaded in DFW remodels. Solution: dedicated circuits for major loads.', urgency: 'Frequent tripping indicates overloading or failing component. Service within 2 weeks.', cost: 'Electrician diagnosis: $150–$300. Dedicated circuit: $250–$600. Panel upgrade: $2,500–$5,000.' },
      'Planning EV charger installation': { guidance: 'DFW EV charger installation: Level 2 (240V, 48A max) is standard home charger. Requires 60A dedicated circuit, 6 AWG wire, NEMA 14-50 outlet or hardwired EVSE. If panel is 100A with full load, upgrade to 200A first ($2,500–$4,500) before adding EV circuit. ONCOR smart meter programs may offer EV-specific TOU rates — inquire. DFW Permit required (Tarrant, Dallas county), typically $75–$200. Install: $800–$2,000 depending on panel proximity to garage.', urgency: 'Planning project — not urgent.', cost: 'EV charger circuit: $800–$2,000. Panel upgrade if needed: $2,500–$4,500.' },
      'Old fuse box or 100A service': { guidance: 'DFW homes with fuse boxes or 60–100A service are undersized for modern loads: 5-ton HVAC alone uses 50–60A startup, plus EV, washer/dryer, range. Upgrade to 200A service: $2,500–$5,000 including new panel, meter base, and ONCOR notification (required). Federal Pacific Stab-Lok and Zinsco panels are fire hazards — replace regardless of amperage. Aluminum wiring (1965–1973 homes): have licensed electrician check connections with CO/ALR devices.', urgency: 'Fuse box or known-defective panel: high priority. 100A service: medium priority, plan within 1–2 years.', cost: 'Panel upgrade: $2,500–$5,000. Whole-home rewire (rare): $8,000–$20,000.' },
      'Planning addition or major renovation': { guidance: 'DFW addition/renovation electrical: (1) Permit required — inspectors check ground fault, arc fault, load calculations. (2) Calculate new total load — may require panel upgrade. (3) Consider EV circuit, solar conduit, smart panel upgrades during renovation when walls are open. (4) All renovation wiring must be 12 AWG minimum (20A circuits) per current NEC. (5) AFCI required for bedrooms, GFCI for wet areas. Labor is most of cost — bundle all future-proofing work into one project.', urgency: 'Plan electrical before renovation begins.', cost: 'Renovation electrical: $3,000–$12,000 depending on scope. Future-proofing additions: $500–$3,000.' },
      'Outlets sparking or warm to touch': { guidance: 'Sparking or warm outlets = immediate safety concern. Causes: loose connections (most common — increases as homes settle in DFW clay), failing outlet device, aluminum wiring connection degradation. Turn off circuit at breaker. Replace outlet ($50–$150 service call). If aluminum wiring home: have all outlets, switches, and fixture connections inspected and fitted with proper connectors. Backstabbed connections (wire pushed into hole rather than screwed) are common in DFW tract homes — replace with screw-terminal connections throughout.', urgency: 'Safety issue — address within 24–48 hours.', cost: 'Single outlet replacement: $50–$150. Whole-home inspection: $300–$600. Aluminum remediation: $2,000–$8,000.' },
      'Generator or battery backup planning': { guidance: 'Post-2021 DFW freeze, backup power is a real need. Options: (1) Portable generator ($800–$3,000) with transfer switch ($500–$1,500) — needs manual setup and fuel. (2) Standby generator (Generac, Kohler) auto-starts, runs on natural gas — $8,000–$20,000 installed, requires gas line and permit. (3) Battery backup (Tesla Powerwall, Franklin Electric) — $12,000–$20,000 for whole-home backup, pairs with solar, silent. Transfer switch or smart panel required for any option. ONCOR may require disconnect notification.', urgency: 'Planning project. Prepare before next winter.', cost: 'Transfer switch: $800–$2,000. Standby generator: $8,000–$20,000. Battery system: $12,000–$25,000.' },
    },
  },
  Roofing: {
    overview: 'DFW roofing is heavily impacted by hail — the DFW metroplex is in the US "Hail Alley" and averages multiple hail events per year significant enough to damage roofing. Most DFW roofs are 30-year architectural shingles; actual lifespan 18–25 years due to UV intensity and thermal cycling. Insurance claims are common and often contentious.',
    situations: ['Roof is 15+ years old', 'Recent hail or wind storm', 'Active leak during rain', 'Granule loss in gutters', 'Evaluating roof for solar installation', 'Insurance claim question'],
    guidance: {
      'Roof is 15+ years old': { guidance: 'DFW roofs at 15 years: inspect for granule loss, curling edges, cracked shingles, and deteriorated flashing. Key locations: ridge cap, pipe boots (almost always fail first — $150–$300 each to replace), valley flashing. If 15 years old with multiple hail events on record (check NOAA), schedule inspection and document condition before next season. Most roofing companies offer free inspection; avoid high-pressure replacement pitches — get an independent assessment.', urgency: 'Proactive — inspect before next hail season (spring in DFW).', cost: 'Inspection: free–$300. Pipe boot replacements: $150–$300 each. Full replacement: $12,000–$22,000 for typical DFW home.' },
      'Recent hail or wind storm': { guidance: 'DFW hail response protocol: (1) Do not allow roofing contractor to inspect during active storm response — wait 48–72 hours. (2) Check attic for daylight or new leaks. (3) Photograph exterior damage you can safely see from ground. (4) Contact your insurance company and request inspection — do not allow contractor to file claim on your behalf without reading the paperwork. (5) Get 2–3 roofing quotes after insurance inspection. (6) Contractors calling door-to-door after hail events are common in DFW — vet carefully.', urgency: 'File insurance claim within 30 days of event per most DFW policies.', cost: 'Insurance deductible: $1,500–$5,000 typical. Out-of-pocket for non-covered damage: varies.' },
      'Active leak during rain': { guidance: 'Active DFW roof leak: (1) Place buckets, protect flooring. (2) Find attic access — water often travels significantly from entry point. (3) Photograph everything for insurance. (4) Call roofing contractor for emergency tarping ($300–$600) if storm ongoing or roof unsafe. (5) Dry out within 24–48 hours to prevent mold — DFW humidity enables rapid mold growth. (6) Do not wait for "next time it rains" — address within 48 hours.', urgency: 'Emergency — active water intrusion.', cost: 'Emergency tarp: $300–$600. Repair after assessment: $500–$3,000+.' },
      'Granule loss in gutters': { guidance: 'Finding granules in DFW gutters is normal in small amounts. Significant granule deposits = accelerated aging. Causes: UV degradation (DFW UV index is extreme May–September), thermal cycling, manufacturer defect, or hail impact. Granule loss exposes asphalt to direct UV — shingle life drops rapidly after this point. If granule loss is widespread across the roof surface, budget for replacement within 3–5 years. Spot granule loss near valleys and pipe boots: repair those sections first.', urgency: 'Moderate — monitor and plan replacement timeline.', cost: 'Inspection to confirm severity: $150–$300. Replacement: $12,000–$22,000.' },
      'Evaluating roof for solar installation': { guidance: 'DFW roof + solar checklist: (1) Roof must have 7+ years remaining life — replace roof before solar if needed. (2) South-facing or west-facing slope preferred (west captures afternoon DFW sun). (3) 4:12 pitch minimum for optimal DFW angle. (4) Assess shading from trees — DFW trees provide valuable shade but impact solar production. (5) Confirm structural load capacity for panels. (6) Some DFW solar installers partner with roofing companies — ask about combined projects. (7) Warranty: solar panel penetrations must be properly flashed — get written warranty on any roof penetrations.', urgency: 'Planning. Roof assessment before committing to solar contract.', cost: 'Roof assessment: $200–$400. Solar: $15,000–$30,000 typical DFW installation.' },
      'Insurance claim question': { guidance: 'DFW roof insurance guidance: (1) Most DFW homeowner policies have separate hail/wind deductibles (1–2% of dwelling coverage, often $5,000–$15,000). (2) ACV vs RCV policies — actual cash value pays depreciated value; replacement cost value pays full replacement minus deductible. Know which you have. (3) You can hire a public adjuster (10–15% of claim) if you dispute the insurance company\’s assessment. (4) Assignment of Benefits is illegal in Texas — contractors cannot take assignment of your claim. (5) Supplemental claims are common when hidden damage is found during replacement.', urgency: 'File claims promptly — most DFW policies have a 1-year filing deadline from storm date.', cost: 'Public adjuster: 10–15% of claim settlement. Independent inspection: $300–$500.' },
    },
  },
  Foundation: {
    overview: 'DFW sits on expansive black clay soil (Blackland Prairie) that swells with moisture and shrinks during drought — causing more residential foundation movement than almost any other market in the US. Foundation issues are not a matter of if but when for most DFW homeowners. Pier and beam foundations (pre-1960s) and post-tension slab (post-1980s) are both common.',
    situations: ['Cracks in drywall or brickwork', 'Doors and windows sticking', 'Gaps between wall and ceiling/floor', 'Foundation company recommended piers', 'After drought or major rain event', 'Buying a home in DFW — inspection question'],
    guidance: {
      'Cracks in drywall or brickwork': { guidance: 'DFW crack analysis: (1) Hairline cracks (<1/16″) in drywall at door corners: normal seasonal movement. Monitor but don\’t panic. (2) Stair-step brick cracks: foundation movement. Get structural engineer assessment (not foundation company — they have financial incentive to recommend repairs). (3) Horizontal cracks in brick: serious — indicates lateral pressure. (4) Cracks wider than 1/4″ or growing: get professional evaluation promptly. (5) Document with photos and measurements — track change over time before deciding to act.', urgency: 'Hairline: monitor. Stair-step: assess within 30 days. Horizontal or growing: urgent.', cost: 'Structural engineer assessment: $400–$800. Foundation repair: $4,000–$20,000+ depending on scope.' },
      'Doors and windows sticking': { guidance: 'Seasonal sticking in DFW is normal — homes move with clay soil moisture changes. Sticking that appears only in wet season then resolves: likely normal. Persistent sticking throughout the year that\’s getting worse: foundation movement. Check: can you slide a business card under the door with it closed? Are multiple doors/windows affected? Is the pattern consistent with one side of the house? Get a structural engineer (not a foundation company) for a definitive assessment.', urgency: 'If progressive and affecting multiple openings: assess within 60 days.', cost: 'Structural engineer: $400–$800. Foundation piers: $1,500–$2,500 each; typical repair: 6–15 piers.' },
      'Gaps between wall and ceiling/floor': { guidance: 'Gaps at wall-ceiling or wall-floor junctions indicate significant foundation movement or shrinkage. In DFW, large gaps (>1/4″) that appear quickly after a drought or major rain event indicate the soil moisture cycle is stressing the foundation. Gap pattern matters: gaps along exterior walls indicate exterior soil movement. Interior gaps may indicate internal support settlement. Get a structural engineer to map the movement pattern before authorizing any repair.', urgency: 'Gaps >1/4″ appearing rapidly: assess within 2 weeks.', cost: 'Structural engineer: $400–$800. Soil moisture management (soaker system): $1,500–$4,000. Piers if needed: $8,000–$25,000.' },
      'Foundation company recommended piers': { guidance: 'DFW foundation company recommendations: (1) Always get a second opinion from an independent structural engineer ($400–$800) — foundation companies earn significant profit on pier installation. (2) Many "failing foundations" in DFW are seasonal movement, not structural failure. (3) Proper soil moisture management (soaker hose system around perimeter) resolves many DFW foundation issues without piers. (4) If piers are needed, get 3 quotes. (5) Transferable lifetime warranties matter — verify the company will exist to honor them.', urgency: 'Second opinion before committing. No urgency unless active structural distress.', cost: 'SE opinion: $400–$800. Soaker system: $1,500–$4,000. Pier installation: $1,500–$2,500 per pier.' },
      'After drought or major rain event': { guidance: 'DFW foundation care after weather extremes: After drought: soil has contracted under foundation — water perimeter slowly and deeply (soaker hose, not sprinklers) to re-expand soil gradually. Rapid re-wetting can cause upward pressure. After major rain: ensure positive drainage away from home (6″ drop in first 10\’ is DFW standard). Clear downspout extensions. Check that flower beds don\’t hold water against foundation. Monitor for 3–6 months post-event before panicking about any movement.', urgency: 'Preventive care — act within 1–2 weeks of event.', cost: 'Soaker hose system: $300–$1,500 DIY. Professional moisture management: $1,500–$4,000.' },
      'Buying a home in DFW — inspection question': { guidance: 'DFW home purchase foundation checklist: (1) Standard home inspection includes visual foundation assessment — not adequate for DFW. (2) Hire a structural engineer separately ($400–$800) — worth every dollar in DFW clay soil. (3) Ask for any previous foundation repair permits and warranties. (4) Review USGS soil maps for the specific address. (5) Look at drainage: does water flow away from the home? (6) Pier repairs disclosed? Get warranty assignment in writing. (7) Foundation issues are common in DFW — don\’t walk away automatically; get the engineer\’s assessment and price any needed repairs.', urgency: 'Before purchase — schedule during option period.', cost: 'Structural engineer: $400–$800. Non-negotiable investment in DFW.' },
    },
  },
  'Pest Control': {
    overview: 'DFW has year-round pest pressure with a unique combination: termites (both subterranean and Formosan), fire ants (aggressive and ubiquitous), mosquitoes (March–November), and occasional scorpion/spider pressure in western DFW. Termite treatment is especially important — DFW soil conditions and climate are highly favorable to subterranean termite activity.',
    situations: ['Annual termite inspection due', 'Found termite swarmers indoors', 'Fire ant mounds everywhere', 'Mosquito problem in yard', 'Found scorpions inside home', 'Rodent evidence (droppings, gnawing)'],
    guidance: {
      'Annual termite inspection due': { guidance: 'DFW termite inspection protocol: (1) Annual inspection is not optional in DFW — subterranean termites cause $1–5B in damage annually in Texas. (2) Inspection should include all wood-soil contact points, foundation perimeter, and crawl space if applicable. (3) Active termite bond ($150–$300/yr) includes annual inspection and treatment if found. (4) Baiting systems (Sentricon) vs liquid treatment (Termidor) — both effective in DFW. (5) Subterranean termites require soil contact — review wood mulch against foundation, wood debris in yard. (6) Formosan termites (more aggressive) are expanding in DFW — know the difference.', urgency: 'Annual — don\’t skip. Termites cause damage before visible signs.', cost: 'Annual bond: $150–$300/yr. Initial treatment if found: $800–$2,500.' },
      'Found termite swarmers indoors': { guidance: 'Indoor termite swarmers (winged termites) = active colony in the structure. This is not an infestation starting — it\’s an established colony swarming. Actions: (1) Collect samples in a jar for identification (flying ants vs termites — key difference: termites have equal-length wings, straight antennae). (2) Call pest control within 24 hours. (3) Do not disturb the swarm location — leave it for the inspector. (4) Swarms typically happen in spring and after rain events in DFW. (5) Request full structural inspection, not just treatment. Treatment: $800–$2,500+ depending on extent.', urgency: 'Emergency — call pest control within 24 hours.', cost: 'Treatment: $800–$2,500. Structural damage repair (if found): varies widely.' },
      'Fire ant mounds everywhere': { guidance: 'DFW fire ant management: (1) Individual mound treatment works but doesn\’t address the colony network — mound moves. (2) Broadcast bait (Amdro, Extinguish Plus) applied to entire yard is the most effective approach — slow-acting but eliminates queens. (3) Spring and fall applications in DFW are most effective when fire ant foraging is active. (4) Professional quarterly treatment: $300–$600/yr. (5) Near structures, heavy infestations: consider professional treatment — fire ants nest in electrical boxes and HVAC equipment. (6) Protect children and pets — DFW fire ant stings cause anaphylaxis in sensitized individuals.', urgency: 'Not emergency unless near children/pets or electrical equipment.', cost: 'DIY broadcast bait: $20–$50 per application. Professional quarterly: $300–$600/yr.' },
      'Mosquito problem in yard': { guidance: 'DFW mosquito control: (1) Source reduction is most effective: eliminate standing water (saucers, low spots, clogged gutters). Even bottle caps hold enough water for mosquito breeding. (2) Professional barrier spray ($75–$150/treatment, monthly March–November) kills adults and lasts 3–4 weeks. (3) Mosquito misting systems ($2,500–$4,000 installed) provide automated treatment — most effective for DFW backyards with pools or water features. (4) BTi dunks ($3–$5 each) for any standing water that can\’t be eliminated (ponds, bird baths). (5) Peak pressure: May–September in DFW; activity extends to November in warm years.', urgency: 'Seasonal nuisance. Address before outdoor season.', cost: 'Professional monthly spray: $900–$1,800/season. Misting system: $2,500–$4,000 installed.' },
      'Found scorpions inside home': { guidance: 'DFW scorpion situation: Striped bark scorpions are the primary species in western DFW (Fort Worth, Tarrant County, Parker County). All scorpions in DFW are venomous but rarely life-threatening except to small children and the allergic. Actions: (1) Seal all entry points — scorpions can fit through a credit card-width gap. (2) Check weather stripping, door sweeps, pipe penetrations. (3) Declutter garage and storage areas — scorpions hide in boxes, shoes, and woodpiles. (4) Professional treatment (exterior perimeter insecticide) reduces food source (insects) and deters entry. (5) Scorpion UV detection: use black light at night to find them.', urgency: 'If found inside: identify entry points within 1 week. Professional treatment if recurring.', cost: 'Professional treatment: $150–$350 per visit. Quarterly program: $400–$700/yr.' },
      'Rodent evidence (droppings, gnawing)': { guidance: 'DFW rodent species: roof rats (attic intrusion, common in DFW trees), Norway rats (ground, less common), house mice. Protocol: (1) Identify type from droppings — roof rat droppings are banana-shaped, mouse droppings are rice-sized. (2) Find entry points — roof rats enter at roofline gaps, tree branches touching home. (3) Seal all entry points (steel wool + caulk, or hardware cloth) before baiting — bait inside causes deaths inside walls. (4) Exterior bait stations are safest approach. (5) Professional exclusion + bait station program: $400–$900. (6) Check HVAC ductwork — rats in DFW attics frequently damage duct insulation.', urgency: 'Address within 1–2 weeks — populations grow rapidly.', cost: 'Professional exclusion + treatment: $400–$900. Ongoing monitoring: $150–$300/yr.' },
    },
  },
};

export default function DFWHomeSystemsFullMasterGuide() {
  const [system, setSystem] = useState('');
  const [situation, setSituation] = useState('');

  const systemData = system ? masterGuide[system] : null;
  const result = system && situation && systemData ? systemData.guidance[situation] : null;

  return (
    <div style={{ background: '#F8F9FA', minHeight: '100vh', color: '#1A2535', fontFamily: 'system-ui, sans-serif', padding: '2rem' }}>
      <div style={{ maxWidth: 900, margin: '0 auto' }}>
        <div style={{ marginBottom: '0.5rem', color: '#1A5276', fontSize: '0.85rem', fontWeight: 600, letterSpacing: 2, textTransform: 'uppercase' }}>ProLnk Reference</div>
        <h1 style={{ fontSize: '2.1rem', fontWeight: 800, marginBottom: '0.35rem', color: '#0A1628′ }}>DFW Home Systems Master Guide</h1>
        <p style={{ color: '#5D6D7E', marginBottom: '2rem', fontSize: '0.97rem' }}>The complete DFW homeowner reference — all 6 major home systems in one place. Select a system and situation for specific guidance.</p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem', marginBottom: '2rem' }}>
          {systems.map(s => (
            <button key={s} onClick={() => { setSystem(s); setSituation(''); }} style={{ background: system === s ? '#0A1628′ : '#FFFFFF', color: system === s ? '#F5E642' : '#1A2535', border: `2px solid ${system === s ? '#0A1628' : '#D5D8DC'}`, borderRadius: 10, padding: '0.9rem 0.5rem', cursor: ’pointer', fontWeight: 700, fontSize: '0.92rem', transition: 'all 0.15s' }}>
              <div style={{ fontSize: '1.5rem', marginBottom: '0.25rem' }}>{systemIcons[s]}</div>
              {s}
            </button>
          ))}
        </div>

        {systemData && (
          <>
            <div style={{ background: '#FFFFFF', borderRadius: 12, padding: '1.5rem', marginBottom: '1.5rem', border: '1px solid #E8ECEF', borderLeft: '5px solid #0A1628′ }}>
              <h2 style={{ color: '#0A1628', fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.75rem' }}>{systemIcons[system]} {system} Overview for DFW</h2>
              <p style={{ color: '#5D6D7E', fontSize: '0.93rem', lineHeight: 1.7 }}>{systemData.overview}</p>
            </div>

            <div style={{ background: '#FFFFFF', borderRadius: 12, padding: '1.5rem', marginBottom: '1.5rem', border: '1px solid #E8ECEF' }}>
              <h2 style={{ color: '#0A1628', fontSize: '1.1rem', fontWeight: 700, marginBottom: '1rem' }}>Select Your Situation</h2>
              <div style={{ display: 'grid', gap: '0.5rem' }}>
                {systemData.situations.map(sit => (
                  <button key={sit} onClick={() => setSituation(sit)} style={{ background: situation === sit ? '#0A1628′ : '#F4F6F7', color: situation === sit ? '#F5E642' : '#1A2535', border: `1px solid ${situation === sit ? '#0A1628' : '#E8ECEF'}`, borderRadius: 8, padding: '0.75rem 1rem', cursor: ’pointer', textAlign: 'left', fontWeight: situation === sit ? 700 : 400, fontSize: '0.9rem', transition: 'all 0.15s' }}>
                    {sit}
                  </button>
                ))}
              </div>
            </div>

            {result && (
              <div style={{ background: '#0A1628', borderRadius: 12, padding: '1.5rem', marginBottom: '2rem', display: 'grid', gap: '1rem' }}>
                <div>
                  <div style={{ color: '#F5E642', fontWeight: 700, fontSize: '0.85rem', marginBottom: '0.5rem' }}>📋 GUIDANCE</div>
                  <p style={{ color: '#CBD5E0', fontSize: '0.92rem', lineHeight: 1.7 }}>{result.guidance}</p>
                </div>
                <div style={{ borderTop: '1px solid #1E3A5F', paddingTop: '1rem', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                  <div>
                    <div style={{ color: '#F5E642', fontWeight: 700, fontSize: '0.82rem', marginBottom: '0.35rem' }}>⏰ URGENCY</div>
                    <p style={{ color: '#A0AEC0', fontSize: '0.87rem', lineHeight: 1.5 }}>{result.urgency}</p>
                  </div>
                  <div>
                    <div style={{ color: '#F5E642', fontWeight: 700, fontSize: '0.82rem', marginBottom: '0.35rem' }}>💰 COST RANGE</div>
                    <p style={{ color: '#A0AEC0', fontSize: '0.87rem', lineHeight: 1.5 }}>{result.cost}</p>
                  </div>
                </div>
              </div>
            )}
          </>
        )}

        {!system && (
          <div style={{ background: '#FFFFFF', borderRadius: 12, padding: '2rem', textAlign: 'center', border: '1px solid #E8ECEF' }}>
            <div style={{ fontSize: '2.5rem', marginBottom: '0.75rem' }}>🏠</div>
            <p style={{ color: '#5D6D7E', fontSize: '0.95rem' }}>Select a home system above to see DFW-specific guidance, common situations, urgency ratings, and cost estimates.</p>
          </div>
        )}

        <div style={{ color: '#AAB7B8', fontSize: '0.78rem', textAlign: 'center', marginTop: '1rem' }}>ProLnk • DFW Home Systems Master Guide • 2026 DFW market reference</div>
      </div>
    </div>
  );
}
