import { useState } from 'react';

const BENEFITS = [
  { id: 'vetted', title: 'Vetted Contractors Only', emoji: '🛡️', detail: 'Every ProLnk contractor is screened for license, insurance, and DFW experience before joining. No unlicensed handymen, no bait-and-switch pricing.' },
  { id: 'fair', title: 'Fair Market Pricing', emoji: '💰', detail: 'ProLnk publishes DFW fair-market rates for every trade. You know if a quote is 30% high before you accept it.' },
  { id: 'nospam', title: 'No Spam Calls', emoji: '🔕', detail: 'Unlike Angi or HomeAdvisor, ProLnk never sells your contact info to 6 contractors at once. One match at a time, on your terms.' },
  { id: 'time', title: 'Time Savings', emoji: '⏱️', detail: 'Skip the hours of Google searches, call tags, and no-shows. ProLnk sends you one qualified, available pro who matches your job.' },
  { id: 'docs', title: 'Job Documentation', emoji: '📂', detail: 'Every job is logged in your Home Health Vault — contractor, date, scope, cost. Invaluable for resale, insurance claims, and warranty disputes.' },
  { id: 'vault', title: 'Home Health Vault', emoji: '🏠', detail: 'Your home’s complete service history in one place. Share it with buyers at resale to justify your asking price and close faster.' },
  { id: 'income', title: 'Origination Rights Income', emoji: '💸', detail: 'When you add your home to ProLnk’s network, you earn a permanent share of platform fees generated by your home’s service activity — forever.' },
];

const PAIN_MAP: Record<string, string> = {
  spam: 'nospam',
  overpriced: 'fair',
  unlicensed: 'vetted',
  slow: 'time',
  nodocs: 'docs',
  resale: 'vault',
  income: 'income',
};

export default function DFWProLnkHowItHelps() {
  const [pain, setPain] = useState('');
  const [highlighted, setHighlighted] = useState('');

  function showFeature() {
    if (!pain) return;
    setHighlighted(PAIN_MAP[pain] || '');
  }

  return (
    <div style={{ background: '#0A1628', minHeight: '100vh', color: '#E8EDF5', fontFamily: 'system-ui, sans-serif', padding: '40px 20px' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <div style={{ color: '#F5E642', fontSize: 13, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 12 }}>FOR DFW HOMEOWNERS</div>
        <h1 style={{ fontSize: 34, fontWeight: 800, margin: '0 0 14px' }}>7 Ways ProLnk Makes DFW Homeownership <span style={{ color: '#F5E642′ }}>Better</span></h1>
        <p style={{ color: '#8FA3BF', fontSize: 15, lineHeight: 1.7, marginBottom: 36 }}>ProLnk was built for the DFW homeowner who's tired of spam calls, inflated quotes, unlicensed contractors, and zero paper trail. Here’s what we actually do differently.</p>

        <div style={{ display: 'grid', gap: 14, marginBottom: 36 }}>
          {BENEFITS.map(b => (
            <div key={b.id} style={{ background: highlighted === b.id ? '#1A3A5C' : '#111E35', borderRadius: 14, padding: 22, border: highlighted === b.id ? '2px solid #F5E642′ : '2px solid transparent', transition: ’all 0.2s' }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 14 }}>
                <span style={{ fontSize: 28 }}>{b.emoji}</span>
                <div>
                  <div style={{ fontWeight: 700, fontSize: 17, marginBottom: 6 }}>{b.title}</div>
                  <div style={{ color: '#8FA3BF', fontSize: 14, lineHeight: 1.6 }}>{b.detail}</div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ background: '#111E35', borderRadius: 16, padding: 28 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 0, marginBottom: 20 }}>🎯 Which Feature Solves Your Biggest Pain Point?</h2>
          <select value={pain} onChange={e => setPain(e.target.value)} style={{ background: '#0A1628', border: '1px solid #1E3A5F', borderRadius: 8, color: '#E8EDF5', padding: '11px 16px', fontSize: 15, width: '100%', marginBottom: 16 }}>
            <option value="">What frustrates you most?</option>
            <option value="spam">Spam calls after requesting a quote</option>
            <option value="overpriced">Not knowing if I'm being overcharged</option>
            <option value="unlicensed">Worrying about unlicensed contractors</option>
            <option value="slow">Wasting hours finding the right pro</option>
            <option value="nodocs">No record of past work done on my home</option>
            <option value="resale">Preparing my home for future resale</option>
            <option value="income">I want my home to generate income</option>
          </select>
          <button onClick={showFeature} style={{ background: '#F5E642', color: '#0A1628', border: 'none', borderRadius: 8, padding: '13px 28px', fontWeight: 800, fontSize: 15, cursor: 'pointer', width: '100%' }}>Show Me the ProLnk Solution</button>
          {highlighted && (
            <div style={{ marginTop: 16, padding: 16, background: '#0A1628', borderRadius: 10, borderLeft: '4px solid #F5E642', fontSize: 14, color: '#C5D5E8′ }}>
              ✅ <strong>{BENEFITS.find(b => b.id === highlighted)?.title}</strong> — {BENEFITS.find(b => b.id === highlighted)?.detail}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
