import { useState } from 'react';

const roles = [
  { id: 'pro', label: '🔧 I\’m a Service Pro', update: 'Charter tier is approaching the 500-pro limit in DFW. June is your last chance to lock in the $149/mo founding rate. Once closed, pricing moves to market rate. Your territory is being mapped now — act before slots fill.' },
  { id: 'homeowner', label: '🏠 I\’m a Homeowner', update: 'Home Health Vault beta is being refined for DFW launch. You\’ll be able to document your home\’s full service history, get AI-powered maintenance alerts, and connect with Charter Pros. Sign up now to be first in queue.' },
  { id: 'investor', label: '📊 I\’m an Investor', update: '5,000+ DFW content pages are live. Charter tier approaching 500-pro cap — this validates demand without paid marketing. Mobile app in development. Seed round materials available on request.' },
  { id: 'partner', label: '🤝 I\’m a Referral Partner', update: 'Network Income System is live with 5 income streams. Every Charter Pro you refer earns you 12% subscription override at $149/mo = $17.88/mo per referred pro, recurring. 4-level cascade activates at 10 referred pros.' },
  { id: 'scout', label: '🗺️ I\’m a Scout', update: 'DFW territory mapping is underway. Scouts who identify and onboard Charter Pros earn origination rights — 1.5% of all job revenue generated by that pro, permanently. June window is critical for territory claims.' },
];

export default function DFWProLnkJuneUpdate2026() {
  const [selected, setSelected] = useState<string | null>(null);

  return (
    <div style={{ background: '#0A1628', minHeight: '100vh', color: '#fff', fontFamily: 'sans-serif', padding: '32px 20px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <div style={{ color: '#F5E642', fontSize: 13, fontWeight: 700, letterSpacing: 2, marginBottom: 8 }}>PROLNK · JUNE 2026 PLATFORM UPDATE</div>
        <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 8 }}>ProLnk June 2026 DFW Platform Update</h1>
        <p style={{ color: '#94a3b8', fontSize: 15, marginBottom: 24 }}>
          June 2026 is a pivotal month. Charter tier is closing, content is live, and DFW launch preparations are in final stages.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 28 }}>
          {[
            { icon: '📄', label: 'DFW Pages Live', val: '5,000+' },
            { icon: '🔧', label: 'Charter Cap', val: '500 Pros' },
            { icon: '📱', label: 'Mobile App', val: 'In Dev' },
            { icon: '🏠', label: 'Vault Beta', val: 'Refining' },
          ].map(s => (
            <div key={s.label} style={{ background: '#111f38', borderRadius: 10, padding: '16px 20px' }}>
              <div style={{ fontSize: 22 }}>{s.icon}</div>
              <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 4 }}>{s.label}</div>
              <div style={{ fontSize: 20, fontWeight: 700, color: '#F5E642′ }}>{s.val}</div>
            </div>
          ))}
        </div>

        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 14 }}>Select Your Role for Your June Update</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 24 }}>
          {roles.map(r => (
            <button
              key={r.id}
              onClick={() => setSelected(selected === r.id ? null : r.id)}
              style={{
                background: selected === r.id ? '#F5E642′ : '#111f38',
                color: selected === r.id ? '#0A1628′ : '#fff',
                border: 'none', borderRadius: 8, padding: '14px 18px',
                textAlign: 'left', cursor: 'pointer', fontWeight: 600, fontSize: 15,
              }}
            >
              {r.label}
            </button>
          ))}
        </div>

        {selected && (
          <div style={{ background: '#1a2f50', border: '2px solid #F5E642', borderRadius: 10, padding: 20, marginBottom: 24 }}>
            <div style={{ fontSize: 13, color: '#F5E642', fontWeight: 700, marginBottom: 6 }}>YOUR JUNE UPDATE</div>
            <p style={{ fontSize: 15, lineHeight: 1.6 }}>{roles.find(r => r.id === selected)?.update}</p>
          </div>
        )}

        <div style={{ background: '#111f38', borderRadius: 10, padding: 20, borderLeft: '4px solid #F5E642′ }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#F5E642', marginBottom: 6 }}>⏳ CHARTER WAITLIST CLOSES AT 500 PROS + 5,000 HOMES</div>
          <p style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.6 }}>
            Once the Charter tier closes, founding rates are locked permanently. Join now at prolnk.io to secure your position before the DFW launch.
          </p>
        </div>
      </div>
    </div>
  );
}