import { useState } from 'react';

const faqCategories = [
  {
    category: '💳 Getting Paid',
    emoji: '💳',
    faqs: [
      {
        q: 'When do I get paid?',
        a: 'Partners are paid on the 1st and 15th of each month. Match commissions earned between the 1st–14th are paid on the 15th. Match commissions earned between the 15th–31st are paid on the 1st of the following month.',
      },
      {
        q: 'What is the minimum payout threshold?',
        a: 'The minimum payout is $50. If your balance is below $50 on a payout date, it rolls forward to the next cycle. There is no cap on maximum payout.',
      },
      {
        q: 'How are payouts delivered?',
        a: 'Payouts are sent via direct deposit (ACH) to your linked bank account, or via Stripe instant payout if you prefer faster access (fees apply). International wire options are available for partners outside the US.',
      },
      {
        q: 'How long does it take for a commission to clear?',
        a: 'Commissions from completed and confirmed jobs clear in 7 business days. This allows time to verify job completion and prevent fraudulent claims.',
      },
      {
        q: 'Can I see my pending earnings before payout?',
        a: 'Yes — your Partner Dashboard shows real-time pending, cleared, and paid earnings broken down by job, tier, and income stream.',
      },
    ],
  },
  {
    category: '📊 Commissions & Tiers',
    emoji: '📊',
    faqs: [
      {
        q: 'What are the commission tiers?',
        a: 'ProLnk has 5 tiers: New (12%, 0–9 matches), Rising (20%, 10–49 matches), Pro (35%, 50–99 matches), Expert (50%, 100–499 matches), and Elite (70%, 500+ matches). Tiers are based on lifetime completed matches, not monthly volume.',
      },
      {
        q: 'Can I lose my tier status?',
        a: 'No. Tiers are earned for life based on cumulative completed matches. You cannot be demoted. However, if your account is suspended for policy violations, tier benefits are paused during the suspension.',
      },
      {
        q: 'How is "match value" calculated?',
        a: 'Match value is the homeowner-confirmed job value — the amount the homeowner paid the pro. ProLnk calculates your commission as a percentage of this confirmed value. Job values are verified against invoice records.',
      },
      {
        q: 'Do I earn commission on jobs I refer but don\’t complete?',
        a: 'No. Direct commissions (Stream 1) are earned only on jobs you personally complete. Network override commissions (Streams 2–3) are earned on jobs completed by pros in your downline.',
      },
      {
        q: 'What is the Charter tier and how does it differ?',
        a: 'Charter is a founding designation (first 500 applicants) that locks in the $149/mo rate permanently and grants priority matching. Commission tiers still advance normally based on match volume.',
      },
    ],
  },
  {
    category: '🌐 Network Cascade',
    emoji: '🌐',
    faqs: [
      {
        q: 'How does the 4-level network cascade work?',
        a: 'When you recruit a pro (Level 1), you earn 1% of their match earnings. Pros they recruit (Level 2) earn you 0.5%. Level 3 earns you 0.25%, and Level 4 earns you 0.1%. This runs automatically — no ongoing action required.',
      },
      {
        q: 'Is there a limit to how many pros I can recruit?',
        a: 'There is no limit on direct recruits (Level 1). You can recruit as many pros as you want. Network depth is capped at 4 levels for override commissions.',
      },
      {
        q: 'How do I track who is in my network?',
        a: 'Your Partner Dashboard has a full network tree view showing all recruited pros by level, their activity status, and your override earnings from each.',
      },
      {
        q: 'What happens to my network income if a recruited pro becomes inactive?',
        a: 'Override income is tied to job completions. If a pro in your network goes inactive, their contribution stops. If they reactivate, your override earnings resume automatically.',
      },
      {
        q: 'Can I lose someone in my downline if they\’re poached by another partner?',
        a: 'No. Network attribution is permanent. The first partner to recruit a pro keeps that relationship for the life of the account. You cannot lose your downline through competitive recruiting.',
      },
    ],
  },
  {
    category: '🏠 Origination Rights',
    emoji: '🏠',
    faqs: [
      {
        q: 'What is the Home Origination Right?',
        a: 'When you onboard a homeowner into ProLnk\’s Home Health Vault, you earn 1.5% of all future platform fees generated by that home — forever. This is the most passive and durable of all 5 income streams.',
      },
      {
        q: 'What counts as "platform fees generated by that home"?',
        a: 'Any match fee, data licensing fee, or Home Health Vault subscription associated with that specific home address contributes to your origination income.',
      },
      {
        q: 'Is the origination right transferable if I leave ProLnk?',
        a: 'No. Origination rights are tied to your active partner account. If your account is terminated, origination income stops. If you choose to pause your account, a grace period of 90 days applies.',
      },
      {
        q: 'How do I get paid for homeowner leads (Stream 4)?',
        a: 'Homeowner override fees are negotiated with your ProLnk regional manager. Typical rates are $25–100 per qualified homeowner depending on the market and service type. These are paid out on the same payout cycle as commissions.',
      },
    ],
  },
  {
    category: '⚠️ Disputes & Edge Cases',
    emoji: '⚠️',
    faqs: [
      {
        q: 'What happens if a homeowner disputes the job after I\’m paid?',
        a: 'If a dispute results in a full or partial refund to the homeowner within 30 days of job completion, your commission is reversed proportionally. After 30 days, commissions are final. ProLnk\’s dispute team investigates all claims before reversals are processed.',
      },
      {
        q: 'What if I complete a job but the homeowner doesn\’t confirm?',
        a: 'Homeowner confirmation is required within 72 hours. If not confirmed, ProLnk sends a reminder. If still unconfirmed after 7 days, the job enters manual review. Providing invoice documentation speeds resolution.',
      },
      {
        q: 'Can I dispute a commission calculation I think is wrong?',
        a: 'Yes. Submit a commission inquiry through your dashboard within 60 days of the payout date. ProLnk\’s audit team will review and respond within 5 business days.',
      },
      {
        q: 'What happens if I suspect someone in my network is committing fraud?',
        a: 'Report suspicious activity through the Partner Support portal. ProLnk has an AI-powered fraud detection system that monitors for lead gaming, fake job reports, and collusion. Fraudulent accounts are terminated and overridden commissions reversed.',
      },
      {
        q: 'What is the consequence of policy violations?',
        a: 'Minor violations result in warnings. Serious violations (lead gaming, fake reviews, soliciting homeowners off-platform) result in account suspension and tier reset. Severe violations result in permanent termination and potential legal action.',
      },
      {
        q: 'Are there any tax implications I should know about?',
        a: 'Yes. Partners earning over $600 in a calendar year will receive a 1099-NEC form by January 31. Partners earning over $20,000/year may also receive a 1099-K. ProLnk recommends consulting a tax professional about self-employment tax obligations.',
      },
    ],
  },
];

export default function ProLnkPartnerIncomeFAQ() {
  const [openItems, setOpenItems] = useState<Record<string, boolean>>({});
  const [activeCategory, setActiveCategory] = useState<string | null>(null);

  const toggleItem = (key: string) => {
    setOpenItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const visibleCategories = activeCategory
    ? faqCategories.filter(c => c.category === activeCategory)
    : faqCategories;

  const totalFaqs = faqCategories.reduce((sum, cat) => sum + cat.faqs.length, 0);

  return (
    <div style={{ background: '#0A1628', minHeight: '100vh', fontFamily: 'system-ui, sans-serif', color: '#fff' }}>
      <div style={{ padding: '80px 24px', textAlign: 'center', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
        <div style={{ maxWidth: 700, margin: '0 auto' }}>
          <div style={{ fontSize: 12, fontWeight: 800, color: '#0A1628', background: '#F5E642', display: 'inline-block', padding: '4px 12px', borderRadius: 6, marginBottom: 16, letterSpacing: 2, textTransform: 'uppercase' }}>Partner Income Guide</div>
          <h1 style={{ fontSize: 46, fontWeight: 900, margin: '0 0 16px', lineHeight: 1.1 }}>Partner Income<br />FAQ</h1>
          <p style={{ fontSize: 17, color: '#a0aec0', lineHeight: 1.7, marginBottom: 12 }}>
            {totalFaqs} questions answered about commissions, payouts, network income, and every edge case you might face as a ProLnk partner.
          </p>
        </div>
      </div>

      <div style={{ maxWidth: 820, margin: '0 auto', padding: '48px 24px' }}>
        <div style={{ marginBottom: 36 }}>
          <p style={{ fontSize: 14, color: '#888', marginBottom: 12 }}>Filter by topic:</p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
            <button
              onClick={() => setActiveCategory(null)}
              style={{ padding: '8px 16px', borderRadius: 8, border: '2px solid', borderColor: !activeCategory ? '#F5E642′ : ’rgba(255,255,255,0.2)', background: !activeCategory ? '#F5E642′ : ’transparent', color: !activeCategory ? '#0A1628′ : '#fff', fontWeight: 700, cursor: ’pointer', fontSize: 13 }}
            >
              All Topics
            </button>
            {faqCategories.map(cat => (
              <button
                key={cat.category}
                onClick={() => setActiveCategory(activeCategory === cat.category ? null : cat.category)}
                style={{ padding: '8px 16px', borderRadius: 8, border: '2px solid', borderColor: activeCategory === cat.category ? '#F5E642′ : ’rgba(255,255,255,0.2)', background: activeCategory === cat.category ? '#F5E642′ : ’transparent', color: activeCategory === cat.category ? '#0A1628′ : '#fff', fontWeight: 700, cursor: ’pointer', fontSize: 13 }}
              >
                {cat.emoji} {cat.category.split(' ').slice(1).join(' ')}
              </button>
            ))}
          </div>
        </div>

        {visibleCategories.map((cat, catIndex) => (
          <section key={cat.category} style={{ marginBottom: 48 }}>
            <h2 style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, color: '#F5E642', display: 'flex', alignItems: 'center', gap: 10 }}>
              {cat.category}
              <span style={{ fontSize: 13, background: 'rgba(245,230,66,0.15)', color: '#F5E642', padding: '2px 8px', borderRadius: 20, fontWeight: 600 }}>{cat.faqs.length} questions</span>
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {cat.faqs.map((faq, faqIndex) => {
                const key = `${catIndex}-${faqIndex}`;
                const isOpen = openItems[key];
                return (
                  <div key={key} style={{ background: isOpen ? 'rgba(245,230,66,0.06)' : 'rgba(255,255,255,0.04)', borderRadius: 12, border: `1px solid ${isOpen ? 'rgba(245,230,66,0.3)' : 'rgba(255,255,255,0.08)'}`, overflow: 'hidden', transition: 'all 0.2s' }}>
                    <button
                      onClick={() => toggleItem(key)}
                      style={{ width: '100%', textAlign: 'left', padding: '18px 22px', background: 'none', border: 'none', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}
                    >
                      <span style={{ fontSize: 15, fontWeight: 600, color: '#fff', lineHeight: 1.5 }}>{faq.q}</span>
                      <span style={{ fontSize: 20, color: isOpen ? '#F5E642′ : '#555', flexShrink: 0, fontWeight: 700, width: 24, textAlign: ’center' }}>
                        {isOpen ? '−' : '+'}
                      </span>
                    </button>
                    {isOpen && (
                      <div style={{ padding: '0 22px 18px', color: '#a0aec0', fontSize: 15, lineHeight: 1.8, borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: 14 }}>
                        {faq.a}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </section>
        ))}

        <section style={{ background: 'rgba(255,255,255,0.04)', borderRadius: 16, padding: 36, marginBottom: 40, border: '1px solid rgba(255,255,255,0.08)', textAlign: 'center' }}>
          <div style={{ fontSize: 40, marginBottom: 12 }}>💬</div>
          <h2 style={{ fontSize: 22, fontWeight: 700, marginBottom: 10 }}>Still have questions?</h2>
          <p style={{ color: '#a0aec0', fontSize: 15, lineHeight: 1.7, marginBottom: 24 }}>Our Partner Success team responds within 4 business hours. You can also connect with experienced partners in our community forum.</p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <button style={{ background: '#F5E642', color: '#0A1628', border: 'none', borderRadius: 8, padding: '12px 28px', fontSize: 15, fontWeight: 700, cursor: 'pointer' }}>Contact Partner Support</button>
            <button style={{ background: 'transparent', color: '#fff', border: '2px solid rgba(255,255,255,0.3)', borderRadius: 8, padding: '12px 28px', fontSize: 15, fontWeight: 700, cursor: 'pointer' }}>Join Partner Community</button>
          </div>
        </section>

        <section style={{ background: '#F5E642', borderRadius: 16, padding: 40, textAlign: 'center' }}>
          <h2 style={{ fontSize: 26, fontWeight: 900, color: '#0A1628', marginBottom: 10 }}>Ready to Start Earning?</h2>
          <p style={{ color: '#1a1a2e', fontSize: 15, lineHeight: 1.7, marginBottom: 24 }}>Join ProLnk as a Charter Partner and lock in the best commission rates before the waitlist closes at 500 spots.</p>
          <button style={{ background: '#0A1628', color: '#F5E642', border: 'none', borderRadius: 10, padding: '14px 36px', fontSize: 16, fontWeight: 800, cursor: 'pointer' }}>Join the Waitlist →</button>
        </section>
      </div>
    </div>
  );
}
