import { useState } from "react";
import PartnerLayout from "@/components/PartnerLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Calculator, Copy, Send, DollarSign, Home, Wrench, TrendingUp, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

const SERVICES: Record<string, { base: number; unit: string; factors: string[] }> = {
  "Roof Inspection": { base: 150, unit: "flat", factors: ["Roof size", "Pitch", "Material type"] },
  "Roof Repair": { base: 450, unit: "per square", factors: ["Damage extent", "Material", "Pitch"] },
  "Full Roof Replacement": { base: 8500, unit: "per square", factors: ["Size", "Material", "Removal"] },
  "HVAC Tune-Up": { base: 89, unit: "flat", factors: ["System age", "Filter replacement"] },
  "HVAC Replacement": { base: 4500, unit: "flat", factors: ["Tonnage", "SEER rating", "Ductwork"] },
  "Gutter Cleaning": { base: 150, unit: "per linear ft", factors: ["Linear footage", "Height"] },
  "Gutter Replacement": { base: 8, unit: "per linear ft", factors: ["Material", "Length"] },
  "Lawn Mowing": { base: 45, unit: "per visit", factors: ["Lot size", "Frequency"] },
  "Landscaping": { base: 1200, unit: "project", factors: ["Scope", "Plants", "Hardscape"] },
  "Interior Painting": { base: 3, unit: "per sq ft", factors: ["Rooms", "Prep work", "Coats"] },
  "Exterior Painting": { base: 2.5, unit: "per sq ft", factors: ["Siding type", "Height", "Prep"] },
  "Plumbing Repair": { base: 175, unit: "flat", factors: ["Complexity", "Parts"] },
  "Electrical Panel": { base: 1800, unit: "flat", factors: ["Amperage", "Permits"] },
  "Window Replacement": { base: 350, unit: "per window", factors: ["Size", "Style", "Glass type"] },
};

export default function QuoteGenerator() {
  const { user } = useAuth();
  const [service, setService] = useState("");
  const [sqft, setSqft] = useState("");
  const [condition, setCondition] = useState("average");
  const [urgency, setUrgency] = useState("standard");
  const [quote, setQuote] = useState<{ low: number; mid: number; high: number } | null>(null);
  const [clientName, setClientName] = useState("");
  const [clientEmail, setClientEmail] = useState("");

  const generateQuote = () => {
    if (!service) { toast.error("Please select a service"); return; }
    const svc = SERVICES[service];
    let base = svc.base;
    if (sqft && svc.unit !== "flat") base = base * (parseFloat(sqft) / 100);
    const conditionMultiplier = condition === "poor" ? 1.35 : condition === "good" ? 0.9 : 1.0;
    const urgencyMultiplier = urgency === "emergency" ? 1.5 : urgency === "rush" ? 1.2 : 1.0;
    const mid = base * conditionMultiplier * urgencyMultiplier;
    setQuote({ low: Math.round(mid * 0.85), mid: Math.round(mid), high: Math.round(mid * 1.2) });
  };

  const copyQuote = () => {
    if (!quote) return;
    const text = `${service} Quote\nLow: $${quote.low.toLocaleString()}\nEstimate: $${quote.mid.toLocaleString()}\nHigh: $${quote.high.toLocaleString()}\n\nGenerated by ProLnk Partner Tools`;
    navigator.clipboard.writeText(text);
    toast.success("Quote copied to clipboard!");
  };

  const createQuoteMutation = trpc.partnerTools.quotes.create.useMutation({
    onError: (err) => toast.error(`Failed: ${err.message}`),
  });
  const sendQuoteMutation = trpc.partnerTools.quotes.send.useMutation({
    onSuccess: () => toast.success(`Quote sent to ${clientEmail}!`),
    onError: (err) => toast.error(`Send failed: ${err.message}`),
  });

  const sendQuote = () => {
    if (!clientEmail.includes("@")) { toast.error("Enter a valid client email"); return; }
    if (!quote) { toast.error("Generate a quote first"); return; }
    createQuoteMutation.mutate({
      clientName: clientName || "Client",
      clientEmail,
      serviceCategory: service,
      description: `${service} — ${condition} condition, ${urgency} urgency`,
      estimatedAmount: String(quote.mid),
    }, {
      onSuccess: (result) => {
        if (result.id) sendQuoteMutation.mutate({ id: result.id });
        else toast.success(`Quote sent to ${clientEmail}!`);
      }
    });
  };

  const exportPDF = () => {
    if (!quote) { toast.error("Generate a quote first"); return; }
    const printContent = `<html><head><title>${service} Quote</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#1e293b}h1{font-size:22px;margin-bottom:4px}.sub{color:#64748b;margin-bottom:24px}table{width:100%;border-collapse:collapse;margin:16px 0}th{background:#f1f5f9;padding:10px 14px;text-align:left;font-size:13px}td{padding:10px 14px;border-bottom:1px solid #e2e8f0;font-size:14px}.footer{margin-top:32px;font-size:11px;color:#94a3b8}@media print{body{padding:20px}}</style>
      </head><body>
      <h1>${service} Estimate</h1>
      <div class="sub">${clientName ? 'Prepared for: ' + clientName + ' &nbsp;|&nbsp; ' : ''}${clientEmail || ''}</div>
      <table><thead><tr><th>Range</th><th>Amount</th></tr></thead><tbody>
      <tr><td>Low Estimate</td><td>$${quote.low.toLocaleString()}</td></tr>
      <tr><td>Mid Estimate</td><td><strong>$${quote.mid.toLocaleString()}</strong></td></tr>
      <tr><td>High Estimate</td><td>$${quote.high.toLocaleString()}</td></tr>
      </tbody></table>
      <p style="font-size:12px;color:#64748b">Factors: ${SERVICES[service]?.factors.join(', ')}</p>
      <div class="footer">Generated by ProLnk Partner Platform &bull; ${new Date().toLocaleDateString()}</div>
      </body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(printContent); w.document.close(); w.print(); }
  };

  return (

    <PartnerLayout>

    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6">
      <div className="max-w-3xl mx-auto">
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-slate-900">Instant Quote Generator</h1>
          <p className="text-slate-500 mt-1">Generate professional estimates in seconds — no spreadsheets needed</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Panel */}
          <Card>
            <CardHeader><CardTitle className="text-base flex items-center gap-2"><Calculator className="w-4 h-4" /> Job Details</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-xs font-medium text-slate-600 mb-1 block">Service Type</label>
                <Select value={service} onValueChange={setService}>
                  <SelectTrigger><SelectValue placeholder="Select service..." /></SelectTrigger>
                  <SelectContent>
                    {Object.keys(SERVICES).map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>

              {service && SERVICES[service].unit !== "flat" && (
                <div>
                  <label className="text-xs font-medium text-slate-600 mb-1 block">
                    Size ({SERVICES[service].unit === "per sq ft" ? "sq ft" : SERVICES[service].unit === "per linear ft" ? "linear feet" : "squares"})
                  </label>
                  <Input type="number" placeholder="e.g. 2000" value={sqft} onChange={e => setSqft(e.target.value)} />
                </div>
              )}

              <div>
                <label className="text-xs font-medium text-slate-600 mb-1 block">Current Condition</label>
                <Select value={condition} onValueChange={setCondition}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="good">Good — minor work needed</SelectItem>
                    <SelectItem value="average">Average — standard repair</SelectItem>
                    <SelectItem value="poor">Poor — significant work needed</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <label className="text-xs font-medium text-slate-600 mb-1 block">Urgency</label>
                <Select value={urgency} onValueChange={setUrgency}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="standard">Standard (1-2 weeks)</SelectItem>
                    <SelectItem value="rush">Rush (3-5 days) +20%</SelectItem>
                    <SelectItem value="emergency">Emergency (24-48 hrs) +50%</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <Button onClick={generateQuote} className="w-full bg-indigo-600 hover:bg-indigo-700">
                <Calculator className="w-4 h-4 mr-2" /> Generate Quote
              </Button>
            </CardContent>
          </Card>

          {/* Quote Output */}
          <div className="space-y-4">
            {quote ? (
              <>
                <Card className="border-indigo-200">
                  <CardHeader><CardTitle className="text-base flex items-center gap-2"><DollarSign className="w-4 h-4 text-indigo-600" /> Quote Range</CardTitle></CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-3 gap-3 mb-4">
                      <div className="text-center p-3 bg-slate-50 rounded-xl">
                        <div className="text-xs text-slate-400 mb-1">Low</div>
                        <div className="text-xl font-bold text-slate-600">${quote.low.toLocaleString()}</div>
                      </div>
                      <div className="text-center p-3 bg-indigo-50 rounded-xl border-2 border-indigo-200">
                        <div className="text-xs text-indigo-500 mb-1 font-medium">Estimate</div>
                        <div className="text-xl font-bold text-indigo-700">${quote.mid.toLocaleString()}</div>
                      </div>
                      <div className="text-center p-3 bg-slate-50 rounded-xl">
                        <div className="text-xs text-slate-400 mb-1">High</div>
                        <div className="text-xl font-bold text-slate-600">${quote.high.toLocaleString()}</div>
                      </div>
                    </div>

                    {service && (
                      <div className="text-xs text-slate-500 mb-3">
                        <div className="font-medium text-slate-700 mb-1">Factors included:</div>
                        {SERVICES[service].factors.map(f => (
                          <div key={f} className="flex items-center gap-1">
                            <span className="w-1 h-1 bg-indigo-400 rounded-full inline-block" /> {f}
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="flex gap-2">
                      <Button size="sm" variant="outline" onClick={copyQuote} className="flex-1 text-xs">
                        <Copy className="w-3 h-3 mr-1" /> Copy
                      </Button>
                      <Button size="sm" variant="outline" className="flex-1 text-xs" onClick={exportPDF}>
                        <FileText className="w-3 h-3 mr-1" /> Export PDF
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader><CardTitle className="text-base text-sm flex items-center gap-2"><Send className="w-4 h-4" /> Send to Client</CardTitle></CardHeader>
                  <CardContent className="space-y-3">
                    <Input placeholder="Client name" value={clientName} onChange={e => setClientName(e.target.value)} />
                    <Input placeholder="Client email" type="email" value={clientEmail} onChange={e => setClientEmail(e.target.value)} />
                    <Button onClick={sendQuote} className="w-full bg-green-600 hover:bg-green-700 text-sm" disabled={createQuoteMutation.isPending || sendQuoteMutation.isPending}>
                      {(createQuoteMutation.isPending || sendQuoteMutation.isPending) ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Sending...</> : <><Send className="w-4 h-4 mr-2" /> Send Quote by Email</>}
                    </Button>
                  </CardContent>
                </Card>
              </>
            ) : (
              <div className="flex items-center justify-center h-full min-h-48 bg-white rounded-xl border-2 border-dashed border-slate-200">
                <div className="text-center text-slate-400">
                  <Calculator className="w-10 h-10 mx-auto mb-2 opacity-30" />
                  <p className="text-sm">Fill in job details and click Generate Quote</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>

    </PartnerLayout>

  );
}
